/**
 * Extended NVIDIA tool/specialised model records.
 *
 * Split from nvidiaCatalogData.js so both files stay under the 500-line
 * anti-entropy size limit.  The first half of the NVIDIA_TOOL_MODELS array
 * lives in nvidiaCatalogData.js; this file exports the second half as
 * NVIDIA_TOOL_MODELS_EXTENDED.  nvidiaCatalogData.js imports and concatenates
 * both halves so that consumers see the same merged NVIDIA_TOOL_MODELS array.
 */

import { OFFICIAL_SOURCE_URLS } from "./nvidiaCatalogConstants.js";

export const NVIDIA_TOOL_MODELS_EXTENDED = [
  {
    modelId: "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning",
    capabilities: ["multimodal_image", "voice_chat", "video", "chat_reasoning"],
    source: "build-nvidia-downloadable",
    sourceUrlOrDiscoveryNote: "https://build.nvidia.com/models",
    freeEndpoint: false,
    downloadableOnly: true,
    endpointType: "downloadable_only",
    requiresSpecialPayload: true,
  },
  {
    modelId: "nvidia/nemotron-nano-12b-v2-vl",
    capabilities: ["multimodal_image"],
    source: "nvidia-api-docs-visual",
    sourceUrlOrDiscoveryNote: OFFICIAL_SOURCE_URLS.llmApis,
    freeEndpoint: true,
    endpointType: "multimodal",
    requiresSpecialPayload: true,
  },
  {
    modelId: "nvidia/llama-3.1-nemotron-nano-vl-8b-v1",
    capabilities: ["multimodal_image"],
    source: "nvidia-api-docs-multimodal",
    sourceUrlOrDiscoveryNote: OFFICIAL_SOURCE_URLS.llmApis,
    freeEndpoint: true,
    endpointType: "multimodal",
    requiresSpecialPayload: true,
  },
  {
    modelId: "nvidia/ising-calibration-1-35b-a3b",
    capabilities: ["multimodal_image", "specialized_hidden"],
    source: "build-nvidia-catalog",
    sourceUrlOrDiscoveryNote: OFFICIAL_SOURCE_URLS.buildModels,
    freeEndpoint: true,
    endpointType: "multimodal",
    requiresSpecialPayload: true,
  },
  {
    modelId: "nvidia/nemoretriever-parse",
    capabilities: ["multimodal_image"],
    source: "nvidia-api-docs-visual",
    sourceUrlOrDiscoveryNote: OFFICIAL_SOURCE_URLS.llmApis,
    freeEndpoint: true,
    endpointType: "multimodal",
    requiresSpecialPayload: true,
  },
  {
    modelId: "nvidia/nemotron-parse",
    capabilities: ["multimodal_image"],
    source: "nvidia-api-docs-visual",
    sourceUrlOrDiscoveryNote: OFFICIAL_SOURCE_URLS.llmApis,
    freeEndpoint: true,
    endpointType: "multimodal",
    requiresSpecialPayload: true,
  },
  {
    modelId: "nvidia/ocdrnet",
    capabilities: ["multimodal_image"],
    source: "nvidia-api-docs-visual",
    sourceUrlOrDiscoveryNote: OFFICIAL_SOURCE_URLS.llmApis,
    freeEndpoint: true,
    deprecatedSoon: true,
    endpointType: "multimodal",
    requiresSpecialPayload: true,
  },
  {
    modelId: "nvidia/retail-object-detection",
    capabilities: ["multimodal_image", "video"],
    source: "build-nvidia-deprecated-free-endpoint",
    sourceUrlOrDiscoveryNote: OFFICIAL_SOURCE_URLS.buildNvidia,
    freeEndpoint: true,
    deprecatedSoon: true,
    endpointType: "video",
    requiresSpecialPayload: true,
  },
  {
    modelId: "nvidia/visual-changenet",
    capabilities: ["multimodal_image"],
    source: "build-nvidia-deprecated-free-endpoint",
    sourceUrlOrDiscoveryNote: OFFICIAL_SOURCE_URLS.buildNvidia,
    freeEndpoint: true,
    deprecatedSoon: true,
    endpointType: "multimodal",
    requiresSpecialPayload: true,
  },
  {
    modelId: "nvidia/cosmos-predict1-5b",
    capabilities: ["video"],
    source: "build-nvidia-free-endpoint",
    sourceUrlOrDiscoveryNote: OFFICIAL_SOURCE_URLS.buildNvidia,
    freeEndpoint: true,
    endpointType: "video",
    requiresSpecialPayload: true,
  },
  {
    modelId: "nvidia/cosmos-transfer2.5-2b",
    capabilities: ["video"],
    source: "build-nvidia-free-endpoint",
    sourceUrlOrDiscoveryNote: OFFICIAL_SOURCE_URLS.buildModels,
    freeEndpoint: true,
    endpointType: "video",
    requiresSpecialPayload: true,
  },
  {
    modelId: "nvidia/synthetic-video-detector",
    capabilities: ["video", "safety"],
    source: "build-nvidia-free-endpoint",
    sourceUrlOrDiscoveryNote: OFFICIAL_SOURCE_URLS.buildModels,
    freeEndpoint: true,
    endpointType: "video",
    requiresSpecialPayload: true,
  },
  {
    modelId: "nvidia/nemotron-voicechat",
    capabilities: ["voice_chat"],
    source: "build-nvidia-free-endpoint",
    sourceUrlOrDiscoveryNote: OFFICIAL_SOURCE_URLS.buildNvidia,
    freeEndpoint: true,
    endpointType: "voice",
    requiresSpecialPayload: true,
  },
  {
    modelId: "nvidia/audio2face-3d-claire-notongue",
    capabilities: ["voice_tts", "specialized_hidden"],
    source: "build-nvidia-deprecated-free-endpoint",
    sourceUrlOrDiscoveryNote: OFFICIAL_SOURCE_URLS.buildNvidia,
    freeEndpoint: true,
    deprecatedSoon: true,
    endpointType: "voice",
    requiresSpecialPayload: true,
  },
  {
    modelId: "nvidia/magpie-tts-flow",
    capabilities: ["voice_tts"],
    source: "build-nvidia-deprecated-free-endpoint",
    sourceUrlOrDiscoveryNote: OFFICIAL_SOURCE_URLS.buildNvidia,
    freeEndpoint: true,
    deprecatedSoon: true,
    endpointType: "voice",
    requiresSpecialPayload: true,
  },
  {
    modelId: "nvidia/bevformer",
    capabilities: ["autonomous_driving"],
    source: "build-nvidia-free-endpoint",
    sourceUrlOrDiscoveryNote: OFFICIAL_SOURCE_URLS.llmApis,
    freeEndpoint: true,
    endpointType: "hosted_specialized",
    requiresSpecialPayload: true,
  },
  {
    modelId: "nvidia/sparsedrive",
    capabilities: ["autonomous_driving"],
    source: "build-nvidia-free-endpoint",
    sourceUrlOrDiscoveryNote: OFFICIAL_SOURCE_URLS.llmApis,
    freeEndpoint: true,
    endpointType: "hosted_specialized",
    requiresSpecialPayload: true,
  },
  {
    modelId: "nvidia/streampetr",
    capabilities: ["autonomous_driving"],
    source: "build-nvidia-free-endpoint",
    sourceUrlOrDiscoveryNote: OFFICIAL_SOURCE_URLS.llmApis,
    freeEndpoint: true,
    endpointType: "hosted_specialized",
    requiresSpecialPayload: true,
  },
  {
    modelId: "nvidia/usdcode",
    capabilities: ["openusd", "chat_coding"],
    source: "nvidia-api-docs-llm",
    sourceUrlOrDiscoveryNote: OFFICIAL_SOURCE_URLS.llmApis,
    freeEndpoint: true,
    endpointType: "chat_completions",
  },
  {
    modelId: "nvidia/genmol",
    capabilities: ["biology"],
    source: "nvidia-api-docs-healthcare",
    sourceUrlOrDiscoveryNote: OFFICIAL_SOURCE_URLS.llmApis,
    freeEndpoint: false,
    endpointType: "hosted_specialized",
    requiresSpecialPayload: true,
  },
  {
    modelId: "nvidia/molmim",
    capabilities: ["biology"],
    source: "nvidia-api-docs-healthcare",
    sourceUrlOrDiscoveryNote: OFFICIAL_SOURCE_URLS.llmApis,
    freeEndpoint: false,
    endpointType: "hosted_specialized",
    requiresSpecialPayload: true,
  },
  {
    modelId: "nvidia/vista3d",
    capabilities: ["biology", "multimodal_image"],
    source: "nvidia-api-docs-healthcare",
    sourceUrlOrDiscoveryNote: OFFICIAL_SOURCE_URLS.llmApis,
    freeEndpoint: false,
    endpointType: "hosted_specialized",
    requiresSpecialPayload: true,
  },
];
