const lines = [
  "PME 移动地球 command overview",
  "",
  "日常使用命令：",
  "- PME 用户启动入口：cmd /c pnpm start:pme",
  "- 启动：cmd /c pnpm dev:phase7b",
  "- 状态：cmd /c pnpm status:phase10a",
  "- 服务健康：cmd /c pnpm health:phase12a",
  "- 日志：cmd /c pnpm logs:phase16a",
  "- 停止并归零：cmd /c pnpm idle:phase15a",
  "- 只停止：cmd /c pnpm stop:phase9c",
  "- 重启：cmd /c pnpm restart:phase11a",
  "- 自检：cmd /c pnpm doctor:phase13a",
  "- 帮助：cmd /c pnpm help:phase14a",
  "",
  "默认验收命令：",
  "- 默认联调：cmd /c pnpm verify:phase7a",
  "- readiness/wait：cmd /c pnpm verify:phase8a-4",
  "- knowledge 总验收：cmd /c pnpm verify:phase21",
  "- knowledge 质量 / infra：cmd /c pnpm verify:phase22",
  "- 真实向量链路：cmd /c pnpm verify:phase23",
  "- 交付资料样例：cmd /c pnpm verify:phase24",
  "- Web 控制台：cmd /c pnpm verify:phase25a",
  "- Chat-first Web：cmd /c pnpm verify:phase26a",
  "- 知识持久化：cmd /c pnpm verify:phase27",
  "- 文档能力闭环：cmd /c pnpm verify:phase28a",
  "- 服务端 RAG chat：cmd /c pnpm verify:phase29a",
  "- 本地安全 workflow：cmd /c pnpm verify:phase30a",
  "- 体验能力集合：cmd /c pnpm verify:phase31a",
  "",
  "企业线验收命令：",
  "- 企业治理：cmd /c pnpm verify:phase32a",
  "- 企业管理面板：cmd /c pnpm verify:phase33a",
  "- 企业安全加固：cmd /c pnpm verify:phase34a",
  "- 用户生命周期：cmd /c pnpm verify:phase35a",
  "- 审计导出：cmd /c pnpm verify:phase36a",
  "- 运维准备 / 备份：cmd /c pnpm verify:phase37a",
  "- 启动准备：cmd /c pnpm verify:phase38a",
  "- 部署预检 UI：cmd /c pnpm verify:phase40a",
  "- 配置向导 UI：cmd /c pnpm verify:phase41a",
  "- 交接清单：cmd /c pnpm verify:phase42a",
  "- 验收报告：cmd /c pnpm verify:phase43a",
  "- 验收报告 UI：cmd /c pnpm verify:phase44a",
  "- 交付候选预演：cmd /c pnpm verify:phase45a",
  "- 交付候选 UI：cmd /c pnpm verify:phase46a",
  "- 企业总览 UI：cmd /c pnpm verify:phase47a",
  "- 企业总览可读性：cmd /c pnpm verify:phase48a",
  "- Web 中文可读性：cmd /c pnpm verify:phase49a",
  "- help 中文可读性：cmd /c pnpm verify:phase50a",
  "- 用户视角首屏可读性：cmd /c pnpm verify:phase51a",
  "- 浏览器渲染实测：cmd /c pnpm verify:phase52a",
  "",
  "Chat 体验验收命令：",
  "- Chat 首屏真实交互：cmd /c pnpm verify:phase53a",
  "- Chat 文件上传真实交互：cmd /c pnpm verify:phase54a",
  "- Chat 多文件上传 / 超限提示：cmd /c pnpm verify:phase55a",
  "- Chat 错误态可读性：cmd /c pnpm verify:phase56a",
  "- Chat 无命中提示：cmd /c pnpm verify:phase57a",
  "- Chat 空输入提示：cmd /c pnpm verify:phase58a",
  "- Provider 列表失败提示：cmd /c pnpm verify:phase59a",
  "- Chat 发送中 / 防重复提交：cmd /c pnpm verify:phase60a",
  "- Chat 完整异常恢复：cmd /c pnpm verify:phase61a",
  "- Chat 会话保存 / 恢复 / 清空：cmd /c pnpm verify:phase62a",
  "- Chat 停止生成 / Abort：cmd /c pnpm verify:phase63a",
  "- Chat 键盘输入 / Enter 发送：cmd /c pnpm verify:phase64a",
  "- Chat 消息操作 / 复制与重发：cmd /c pnpm verify:phase65a",
  "- Chat 引用可读化 / 单条引用复制：cmd /c pnpm verify:phase66a",
  "- Chat 过程状态 / 检索生成反馈：cmd /c pnpm verify:phase67a",
  "- Chat Markdown-lite / 列表代码链接：cmd /c pnpm verify:phase68a",
  "- Chat 代码块工具 / inline code：cmd /c pnpm verify:phase69a",
  "- Chat 表格引用分隔线：cmd /c pnpm verify:phase70a",
  "- Chat 长回答视图跟随：cmd /c pnpm verify:phase71a",
  "- Chat 输入区体验：cmd /c pnpm verify:phase72a",
  "- Chat 移动端视图：cmd /c pnpm verify:phase73a",
  "- Chat 首屏极简入口：cmd /c pnpm verify:phase74a",
  "- Chat 最终体验表层：cmd /c pnpm verify:phase75a",
  "- Chat 命令中心 / 模型配置卡片：cmd /c pnpm verify:phase76a",
  "- Chat 模型选择持久化：cmd /c pnpm verify:phase76b",
  "- Chat 配置向导体验打磨：cmd /c pnpm verify:phase76c",
  "- Chat 配置生效状态提示：cmd /c pnpm verify:phase76d",
  "- Chat 当前模型可用性检测：cmd /c pnpm verify:phase76e",
  "- Chat 一键应用并检测模型：cmd /c pnpm verify:phase76f",
  "- Chat 模型配置高级项折叠：cmd /c pnpm verify:phase76g",
  "- Chat 输入区模型状态条：cmd /c pnpm verify:phase76h",
  "- Chat 发送前智能提示：cmd /c pnpm verify:phase76i",
  "- Chat 顶部模型选择弱化：cmd /c pnpm verify:phase76j",
  "- Chat 输入区动作减负：cmd /c pnpm verify:phase76k",
  "- Chat 资料入库回执：cmd /c pnpm verify:phase76l",
  "- Chat 知识命中引用细节：cmd /c pnpm verify:phase76m",
  "- Chat API Key 一键添加模型：cmd /c pnpm verify:phase76n",
  "- Chat API Key 自动识别模型：cmd /c pnpm verify:phase76o",
  "- Chat API Key 多能力模型匹配：cmd /c pnpm verify:phase76p",
  "- Chat 用户 API 表格厂商覆盖：cmd /c pnpm verify:phase76q",
  "- Chat 通用 OpenAI-compatible 运行时接入：cmd /c pnpm verify:phase76r",
  "- Chat API Key 模型列表深度探测：cmd /c pnpm verify:phase76s",
  "- Chat 四条主线聚合体验：cmd /c pnpm verify:phase77a",
  "- 全球发布 readiness 预检：cmd /c pnpm verify:phase78a",
  "- PME 用户启动入口预检：cmd /c pnpm verify:phase79a",
  "- Web 首次使用向导：cmd /c pnpm verify:phase80a",
  "- 启动后自动打开浏览器：cmd /c pnpm verify:phase81a",
  "- Chat 模型配置可见入口：cmd /c pnpm verify:phase82a",
  "- Chat 失败恢复建议：cmd /c pnpm verify:phase83a",
  "- Chat 模型配置下一步动作：cmd /c pnpm verify:phase84a",
  "- Chat 模型配置失败路径实测：cmd /c pnpm verify:phase85a",
  "- Chat 模型配置成功路径实测：cmd /c pnpm verify:phase86a",
  "- Chat 模型配置状态解释：cmd /c pnpm verify:phase87a",
  "- Chat 配置后首问实测：cmd /c pnpm verify:phase88a",
  "- Chat 模型配置重启恢复：cmd /c pnpm verify:phase89a",
  "- Chat 重启恢复状态可读性：cmd /c pnpm verify:phase90a",
  "- Chat 恢复配置失效修复提示：cmd /c pnpm verify:phase91a",
  "- Chat 恢复配置重新检测闭环：cmd /c pnpm verify:phase92a",
  "- Chat 修复后继续刚才问题：cmd /c pnpm verify:phase93a",
  "- Chat 修复成功提示减负：cmd /c pnpm verify:phase94a",
  "- Chat 配置成功后自然回到聊天：cmd /c pnpm verify:phase95a",
  "- Chat 配置成功后第一条消息体验：cmd /c pnpm verify:phase96a",
  "- Chat 模型配置总回归：cmd /c pnpm verify:phase97a",
  "- Chat 模型配置用户旅程：cmd /c pnpm verify:phase98a",
  "- Chat 模型配置视觉终检：cmd /c pnpm verify:phase99a",
  "- Chat 模型配置阶段封板：cmd /c pnpm verify:phase100a",
  "- Chat 模型配置文案终封：cmd /c pnpm verify:phase101a",
  "",
  "模型导入验收：",
  "- API Key 模型导入：cmd /c pnpm verify:phase8a-model-import",
  "- 企业聚合验收：cmd /c pnpm verify:enterprise",
  "",
  "知识库细分验收：",
  "- knowledge entry：cmd /c pnpm verify:phase21a",
  "- source load：cmd /c pnpm verify:phase21b",
  "- console knowledge chain：cmd /c pnpm verify:phase21c",
  "",
  "Web 入口：",
  "- http://127.0.0.1:3100/ui",
  "",
  "当前冻结边界：",
  "- 默认 /chat 主链仍是 NVIDIA single-provider。",
  "- /chat/rag 与 /chat/rag/stream 是有边界的知识增强入口。",
  "- 默认 knowledge 模式仍是 local-keyword；真实向量链路需要显式配置后通过 verify:phase23 验证。",
  "- health:phase12a 只检查本地服务 /health/check 是否 ready；真实 provider 烟测请运行 verify:phase7a-1 或 verify:phase7a。",
  "- 企业总览、验收报告、交付候选预演都是只读视图，不代表 release automation 已完成。",
  "- 当前不代表完整 IAM/SSO、治理自动化、外部爬取、生产 GraphRAG、长期记忆治理平台或发布自动化最终形态。",
  "",
  "help 只读说明：",
  "- 不启动服务。",
  "- 不停止或重启进程。",
  "- 不调用 provider。",
  "- 不刷新 evidence。",
  "- 不修改运行数据。",
];

console.log(lines.join("\n"));
