import { computeCapabilityAtomId } from "./capabilityAtomHash.js";

export function getSyntheticCapabilityAtoms() {
  return [
    createAtom({
      title: "owner_daily_status_check",
      description: "Read owner-facing local status evidence and summarize today's state.",
      capabilityTags: ["owner", "daily_status", "local_readout"],
      inputContract: { taskText: "string" },
      outputContract: { statusSummary: "string", nextActions: "string[]" },
      deps: ["evidence_replay_summary"],
      positiveSources: ["Phase1939P usability gate"],
      negativeSources: [],
      constraintSources: ["No Provider call", "No secret read"],
      riskLevel: "low",
      allowedModes: ["normal", "tianshu"],
      allowedEffects: ["read_evidence", "summarize", "dry_run_plan"],
      evidenceRefs: ["apps/ai-gateway-service/evidence/phase1939p/no-human-explanation-usability-gate-result.json"],
      rollbackNote: "Remove owner daily status atom from synthetic registry.",
    }),
    createAtom({
      title: "evidence_replay_summary",
      description: "Replay sanitized local evidence and explain blockers without upgrading claims.",
      capabilityTags: ["evidence", "replay", "summary"],
      inputContract: { evidencePaths: "string[]" },
      outputContract: { blockerSummary: "string", evidenceCoherenceScore: "number" },
      deps: [],
      positiveSources: ["Phase1940P final gate"],
      negativeSources: [],
      constraintSources: ["No raw secret", "No Provider call"],
      riskLevel: "low",
      allowedModes: ["normal", "god", "tianshu"],
      allowedEffects: ["read_evidence", "summarize", "risk_assess"],
      evidenceRefs: ["apps/ai-gateway-service/evidence/phase1940p/production-grade-evidence-final-gate-result.json"],
      rollbackNote: "Remove evidence replay atom from synthetic registry.",
    }),
    createAtom({
      title: "secret_safety_check",
      description: "Read secret safety verifier output and preserve secret-safety boundary.",
      capabilityTags: ["security", "secret_safety", "regression"],
      inputContract: { verifierName: "string" },
      outputContract: { secretSafetyPassed: "boolean" },
      deps: ["evidence_replay_summary"],
      positiveSources: ["Phase1938P regression gate"],
      negativeSources: [],
      constraintSources: ["No raw environment file read", "No auth config file read"],
      riskLevel: "low",
      allowedModes: ["tianshu"],
      allowedEffects: ["read_evidence", "risk_assess"],
      evidenceRefs: ["apps/ai-gateway-service/evidence/phase1938p/continuous-safety-regression-gate-result.json"],
      rollbackNote: "Remove secret safety atom from synthetic registry.",
    }),
    createAtom({
      title: "ui_smoke_check",
      description: "Read UI smoke evidence and report owner-facing availability.",
      capabilityTags: ["ui", "smoke", "owner_visibility"],
      inputContract: { smokeName: "string" },
      outputContract: { uiSmokePassed: "boolean", visibleMarkers: "string[]" },
      deps: ["evidence_replay_summary"],
      positiveSources: ["Phase1938P regression gate"],
      negativeSources: [],
      constraintSources: ["No browser mutation"],
      riskLevel: "low",
      allowedModes: ["normal", "tianshu"],
      allowedEffects: ["read_evidence", "summarize"],
      evidenceRefs: ["apps/ai-gateway-service/evidence/phase1938p/continuous-safety-regression-gate-result.json"],
      rollbackNote: "Remove UI smoke atom from synthetic registry.",
    }),
    createAtom({
      title: "provider_stability_check",
      description: "Check whether guarded Provider stability is verified while preserving NVIDIA timeout-blocked evidence.",
      capabilityTags: ["provider", "stability", "nvidia"],
      inputContract: { providerId: "nvidia", modelId: "string", credentialRef: "credentialRef" },
      outputContract: { providerStable: "boolean", blocker: "string|null" },
      deps: ["evidence_replay_summary"],
      positiveSources: [],
      negativeSources: [
        "Phase1932P blocker=safe_provider_call_implementation_missing",
        "Phase1955P failureReason=nvidia_request_timeout latencyMs=30025",
        "Phase1955P-Retry failureReason=nvidia_request_timeout timeoutStage=provider_fetch_or_response_wait_timeout latencyMs=60029",
      ],
      constraintSources: [
        "Requires explicit provider authorization",
        "Preserve provider_stability_not_verified",
        "NVIDIA route is timeout_blocked until route repair or alternative provider authorization",
        "Phase1956P alternative provider authorization packet prepared; still no Provider stability claim",
        "Do not enter single-provider stability test from timeout-blocked evidence",
      ],
      riskLevel: "blocked",
      allowedModes: ["tianshu"],
      allowedEffects: ["read_evidence", "risk_assess"],
      requiresProvider: true,
      evidenceRefs: [
        "apps/ai-gateway-service/evidence/phase1932p/guarded-real-provider-stability-test-result.json",
        "apps/ai-gateway-service/evidence/phase1955p/phase1955p-seal-result.json",
        "apps/ai-gateway-service/evidence/phase1955p_retry/phase1955p-retry-seal-result.json",
        "apps/ai-gateway-service/evidence/phase1955p_retry_fail/phase1955p-retry-fail-seal-result.json",
        "apps/ai-gateway-service/evidence/phase1956p_alt_provider/alternative-provider-authorization-seal-result.json",
      ],
      blocker: "provider_stability_not_verified",
      blockerExplanation: "NVIDIA guarded one-shot route timed out twice; route is timeout_blocked. Phase1956P alternative provider authorization packet prepared, but Provider stability remains unverified until a separately approved one-shot succeeds.",
      executionAllowed: false,
      rollbackNote: "Remove provider stability atom or keep blocked until Phase1932P passes.",
    }),
    createAtom({
      title: "rollback_drill_check",
      description: "Check rollback drill evidence and distinguish dry-run from real rollback.",
      capabilityTags: ["rollback", "drill", "safety"],
      inputContract: { rollbackEvidence: "string" },
      outputContract: { rollbackDryRunPassed: "boolean", realRollbackExecuted: "boolean" },
      deps: ["evidence_replay_summary"],
      positiveSources: ["Phase1937P rollback dry-run"],
      negativeSources: ["No owner real rollback authorization"],
      constraintSources: ["Do not run git reset", "Do not run git clean"],
      riskLevel: "medium",
      allowedModes: ["god", "tianshu"],
      allowedEffects: ["read_evidence", "risk_assess", "summarize"],
      evidenceRefs: ["apps/ai-gateway-service/evidence/phase1937p/rollback-drill-evidence-result.json"],
      rollbackNote: "Remove rollback drill atom from synthetic registry.",
    }),
  ];
}

function createAtom(overrides) {
  const atom = {
    atomId: "",
    version: "1.0.0",
    description: "",
    capabilityTags: [],
    inputContract: {},
    outputContract: {},
    deps: [],
    positiveSources: [],
    negativeSources: [],
    constraintSources: [],
    riskLevel: "low",
    allowedModes: ["tianshu"],
    allowedEffects: ["read_evidence"],
    requiresHumanApproval: false,
    requiresProvider: false,
    requiresSecret: false,
    supportsDryRun: true,
    evidenceRefs: [],
    rollbackNote: "",
    ...overrides,
  };
  atom.atomId = computeCapabilityAtomId(atom);
  return atom;
}
