export const MODEL_DISCOVERY_TIMEOUT_MS = 6_000;
export const MAX_DISCOVERED_MODELS = 120;
export const CAPABILITY_ORDER = [
  "chat",
  "vision",
  "reasoning",
  "coding",
  "tool-use",
  "structured-output",
  "image-generation",
  "audio-input",
  "speech-output",
  "video-generation",
  "embedding",
  "rerank",
  "moderation",
  "summary",
];

export const CHAT_EXCLUSIVE_BLOCKERS = new Set([
  "audio-input",
  "speech-output",
  "image-generation",
  "video-generation",
  "embedding",
  "rerank",
  "moderation",
]);

const PROVIDER_CATALOG_CORE = [
  {
    family: "local-fake",
    providerId: "local-fake-provider",
    displayName: "Local Fake Provider",
    prefixes: [{ value: "fake-", unique: true, confidence: "test-only" }],
    testOnly: true,
    availableForChat: true,
    defaultModels: [
      { modelId: "local-fake-model", modelDisplayName: "Local Fake Model", capabilities: ["chat", "summary"] },
      { modelId: "phase76o-alt-model", modelDisplayName: "Phase 76O Alt Model", capabilities: ["chat", "summary"] },
    ],
    reason: "Detected a local fake test key. This is only for local verification.",
  },
  {
    family: "nvidia",
    providerId: "nvidia",
    displayName: "NVIDIA",
    prefixes: [{ value: "nvapi-", unique: true, confidence: "high" }],
    availableForChat: true,
    endpoint: "https://integrate.api.nvidia.com/v1",
    modelListPath: "/models",
    modelListValidatesCredential: false,
    defaultModels: [
      { modelId: "meta/llama-3.1-8b-instruct", modelDisplayName: "Meta Llama 3.1 8B Instruct", capabilities: ["chat", "summary"] },
      { modelId: "meta/llama-3.3-70b-instruct", modelDisplayName: "Meta Llama 3.3 70B Instruct", capabilities: ["chat", "reasoning", "summary"] },
      { modelId: "qwen/qwen2.5-coder-32b-instruct", modelDisplayName: "Qwen 2.5 Coder 32B Instruct", capabilities: ["chat", "coding", "summary"] },
    ],
    reason: "Detected an NVIDIA API key prefix. The system can discover NVIDIA models and add chat-capable ones to the current runtime.",
  },
  {
    family: "openrouter",
    providerId: "openrouter",
    displayName: "OpenRouter",
    prefixes: [{ value: "sk-or-v1-", unique: true, confidence: "high" }],
    availableForChat: true,
    endpoint: "https://openrouter.ai/api/v1",
    modelListPath: "/models?output_modalities=all",
    defaultModels: [
      { modelId: "openai/gpt-4o-mini", modelDisplayName: "OpenAI GPT-4o Mini", capabilities: ["chat", "vision", "summary"] },
      { modelId: "anthropic/claude-sonnet-4.5", modelDisplayName: "Claude Sonnet 4.5", capabilities: ["chat", "vision", "coding", "reasoning", "summary"] },
      { modelId: "google/gemini-2.5-pro", modelDisplayName: "Gemini 2.5 Pro", capabilities: ["chat", "vision", "coding", "reasoning", "summary"] },
    ],
    reason: "Detected an OpenRouter key prefix. The system can discover OpenRouter models, read their modality metadata, and let you choose a chat-executable model.",
  },
  {
    family: "groq",
    providerId: "groq",
    displayName: "Groq",
    prefixes: [{ value: "gsk_", unique: true, confidence: "high" }],
    availableForChat: true,
    endpoint: "https://api.groq.com/openai/v1",
    modelListPath: "/models",
    defaultModels: [
      { modelId: "llama-3.1-8b-instant", modelDisplayName: "Llama 3.1 8B Instant", capabilities: ["chat", "summary"] },
      { modelId: "llama-3.3-70b-versatile", modelDisplayName: "Llama 3.3 70B Versatile", capabilities: ["chat", "reasoning", "summary"] },
      { modelId: "whisper-large-v3", modelDisplayName: "Whisper Large v3", capabilities: ["audio-input"] },
    ],
    reason: "Detected a Groq key prefix. The system can discover Groq OpenAI-compatible chat models.",
  },
  {
    family: "xai",
    providerId: "xai",
    displayName: "xAI",
    prefixes: [{ value: "xai-", unique: true, confidence: "high" }],
    availableForChat: true,
    endpoint: "https://api.x.ai/v1",
    modelListPath: "/models",
    defaultModels: [
      { modelId: "grok-3-mini", modelDisplayName: "Grok 3 Mini", capabilities: ["chat", "reasoning", "summary"] },
      { modelId: "grok-beta", modelDisplayName: "Grok Beta", capabilities: ["chat", "summary"] },
      { modelId: "grok-2-vision-1212", modelDisplayName: "Grok 2 Vision", capabilities: ["chat", "vision", "summary"] },
    ],
    reason: "Detected an xAI key prefix. The system can discover xAI OpenAI-compatible chat models.",
  },
  {
    family: "cerebras",
    providerId: "cerebras",
    displayName: "Cerebras",
    prefixes: [{ value: "csk-", unique: true, confidence: "high" }],
    availableForChat: true,
    endpoint: "https://api.cerebras.ai/v1",
    modelListPath: "/models",
    defaultModels: [
      { modelId: "llama3.1-8b", modelDisplayName: "Llama 3.1 8B", capabilities: ["chat", "summary"] },
      { modelId: "llama-3.3-70b", modelDisplayName: "Llama 3.3 70B", capabilities: ["chat", "reasoning", "summary"] },
    ],
    reason: "Detected a Cerebras key prefix. The system can discover Cerebras OpenAI-compatible chat models.",
  },
  {
    family: "perplexity",
    providerId: "perplexity",
    displayName: "Perplexity",
    prefixes: [{ value: "pplx-", unique: true, confidence: "medium" }],
    availableForChat: true,
    endpoint: "https://api.perplexity.ai",
    modelListPath: "/models",
    defaultModels: [
      { modelId: "sonar", modelDisplayName: "Sonar", capabilities: ["chat", "summary"] },
      { modelId: "sonar-pro", modelDisplayName: "Sonar Pro", capabilities: ["chat", "reasoning", "summary"] },
    ],
    reason: "Detected a Perplexity-style key prefix. The system can try Perplexity's OpenAI-compatible chat path.",
  },
  {
    family: "openai",
    providerId: "openai",
    displayName: "OpenAI",
    prefixes: [
      { value: "sk-proj-", unique: true, confidence: "high" },
      { value: "sk-", unique: false, confidence: "ambiguous" },
    ],
    availableForChat: true,
    endpoint: "https://api.openai.com/v1",
    modelListPath: "/models",
    defaultModels: [
      { modelId: "gpt-4o-mini", modelDisplayName: "GPT-4o Mini", capabilities: ["chat", "vision", "tool-use", "structured-output", "summary"] },
      { modelId: "gpt-4o", modelDisplayName: "GPT-4o", capabilities: ["chat", "vision", "reasoning", "tool-use", "structured-output", "summary"] },
      { modelId: "o4-mini", modelDisplayName: "o4 Mini", capabilities: ["chat", "reasoning", "coding", "tool-use", "structured-output", "summary"] },
      { modelId: "gpt-image-1", modelDisplayName: "GPT Image 1", capabilities: ["image-generation"] },
      { modelId: "text-embedding-3-large", modelDisplayName: "Text Embedding 3 Large", capabilities: ["embedding"] },
      { modelId: "whisper-1", modelDisplayName: "Whisper 1", capabilities: ["audio-input"] },
      { modelId: "tts-1", modelDisplayName: "TTS 1", capabilities: ["speech-output"] },
    ],
    reason: "Detected an OpenAI-style key. Generic sk- keys are ambiguous, so the system avoids probing multiple vendors automatically.",
  },
  {
    family: "deepseek",
    providerId: "deepseek",
    displayName: "DeepSeek",
    prefixes: [{ value: "sk-", unique: false, confidence: "ambiguous" }],
    availableForChat: true,
    endpoint: "https://api.deepseek.com/v1",
    modelListPath: "/models",
    defaultModels: [
      { modelId: "deepseek-chat", modelDisplayName: "DeepSeek Chat", capabilities: ["chat", "coding", "summary"] },
      { modelId: "deepseek-reasoner", modelDisplayName: "DeepSeek Reasoner", capabilities: ["chat", "reasoning", "coding", "summary"] },
    ],
    reason: "Generic sk- keys may belong to DeepSeek; choose this provider to probe only DeepSeek.",
  },
  {
    family: "together",
    providerId: "together",
    displayName: "Together AI",
    prefixes: [{ value: "sk-", unique: false, confidence: "ambiguous" }],
    availableForChat: true,
    endpoint: "https://api.together.xyz/v1",
    modelListPath: "/models",
    defaultModels: [
      { modelId: "meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo", modelDisplayName: "Llama 3.1 8B Instruct Turbo", capabilities: ["chat", "summary"] },
      { modelId: "meta-llama/Llama-3.3-70B-Instruct-Turbo", modelDisplayName: "Llama 3.3 70B Instruct Turbo", capabilities: ["chat", "reasoning", "summary"] },
      { modelId: "Qwen/Qwen2.5-Coder-32B-Instruct", modelDisplayName: "Qwen 2.5 Coder 32B Instruct", capabilities: ["chat", "coding", "summary"] },
    ],
    reason: "Generic sk- keys may belong to Together AI; choose this provider to probe only Together.",
  },
  {
    family: "mistral",
    providerId: "mistral",
    displayName: "Mistral",
    prefixes: [{ value: "sk-", unique: false, confidence: "ambiguous" }],
    availableForChat: true,
    endpoint: "https://api.mistral.ai/v1",
    modelListPath: "/models",
    defaultModels: [
      { modelId: "mistral-small-latest", modelDisplayName: "Mistral Small Latest", capabilities: ["chat", "tool-use", "summary"] },
      { modelId: "mistral-large-latest", modelDisplayName: "Mistral Large Latest", capabilities: ["chat", "reasoning", "coding", "tool-use", "summary"] },
      { modelId: "pixtral-large-latest", modelDisplayName: "Pixtral Large Latest", capabilities: ["chat", "vision", "summary"] },
    ],
    reason: "Generic sk- keys may belong to Mistral; choose this provider to probe only Mistral.",
  },
  {
    family: "moonshot",
    providerId: "moonshot",
    displayName: "Moonshot AI",
    prefixes: [{ value: "sk-", unique: false, confidence: "ambiguous" }],
    availableForChat: true,
    endpoint: "https://api.moonshot.ai/v1",
    modelListPath: "/models",
    defaultModels: [
      { modelId: "moonshot-v1-8k", modelDisplayName: "Moonshot v1 8K", capabilities: ["chat", "summary"] },
      { modelId: "moonshot-v1-32k", modelDisplayName: "Moonshot v1 32K", capabilities: ["chat", "summary"] },
      { modelId: "kimi-k2-instruct", modelDisplayName: "Kimi K2 Instruct", capabilities: ["chat", "coding", "reasoning", "summary"] },
    ],
    reason: "Generic sk- keys may belong to Moonshot AI; choose this provider to probe only Moonshot.",
  },
  {
    family: "siliconflow",
    providerId: "siliconflow",
    displayName: "SiliconFlow",
    prefixes: [{ value: "sk-", unique: false, confidence: "ambiguous" }],
    availableForChat: true,
    endpoint: "https://api.siliconflow.cn/v1",
    modelListPath: "/models",
    defaultModels: [
      { modelId: "Qwen/Qwen2.5-7B-Instruct", modelDisplayName: "Qwen 2.5 7B Instruct", capabilities: ["chat", "summary"] },
      { modelId: "deepseek-ai/DeepSeek-V3", modelDisplayName: "DeepSeek V3", capabilities: ["chat", "coding", "summary"] },
      { modelId: "BAAI/bge-m3", modelDisplayName: "BGE M3", capabilities: ["embedding"] },
      { modelId: "BAAI/bge-reranker-v2-m3", modelDisplayName: "BGE Reranker v2 M3", capabilities: ["rerank"] },
    ],
    reason: "Generic sk- keys may belong to SiliconFlow; choose this provider to probe only SiliconFlow.",
  },
];

import { PROVIDER_CATALOG_EXTENDED } from "./providerCatalogExtended.js";

export const PROVIDER_CATALOG = [...PROVIDER_CATALOG_CORE, ...PROVIDER_CATALOG_EXTENDED];
