/**
 * providerCatalogExtended.js
 *
 * Extended provider catalog entries (DashScope through Anthropic).
 * Extracted from providerCatalog.js to keep the main file under 500 lines.
 */

export const PROVIDER_CATALOG_EXTENDED = [
  {
    family: "dashscope",
    providerId: "dashscope",
    displayName: "DashScope",
    prefixes: [{ value: "sk-", unique: false, confidence: "ambiguous" }],
    hints: ["dashscope", "dashscope.aliyuncs.com", "阿里百炼", "百炼", "通义", "qwen"],
    credentialPatterns: [
      { pattern: /^sk-[a-f0-9]{32}$/i, unique: true, confidence: "dashscope-key-shape" },
    ],
    availableForChat: true,
    endpoint: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    modelListPath: "/models",
    defaultModels: [
      { modelId: "qwen-plus", modelDisplayName: "Qwen Plus", capabilities: ["chat", "summary"] },
      { modelId: "qwen-max", modelDisplayName: "Qwen Max", capabilities: ["chat", "reasoning", "summary"] },
      { modelId: "qwen-vl-plus", modelDisplayName: "Qwen VL Plus", capabilities: ["chat", "vision", "summary"] },
      { modelId: "text-embedding-v3", modelDisplayName: "Text Embedding v3", capabilities: ["embedding"] },
      { modelId: "wanx2.1-t2i-plus", modelDisplayName: "Wanx Image", capabilities: ["image-generation"] },
    ],
    reason: "Generic sk- keys may belong to DashScope; choose this provider to probe only DashScope.",
  },
  {
    family: "tencent-hunyuan",
    providerId: "tencent-hunyuan",
    displayName: "Tencent Hunyuan",
    prefixes: [{ value: "sk-", unique: false, confidence: "ambiguous" }],
    hints: ["tencent", "hunyuan", "混元", "腾讯", "api.hunyuan.cloud.tencent.com"],
    availableForChat: true,
    endpoint: "https://api.hunyuan.cloud.tencent.com/v1",
    modelListPath: "/models",
    defaultModels: [
      { modelId: "hunyuan-lite", modelDisplayName: "Hunyuan Lite", capabilities: ["chat", "summary"] },
      { modelId: "hunyuan-turbo", modelDisplayName: "Hunyuan Turbo", capabilities: ["chat", "reasoning", "summary"] },
      { modelId: "hunyuan-t1-latest", modelDisplayName: "Hunyuan T1 Latest", capabilities: ["chat", "reasoning", "summary"] },
    ],
    reason: "Generic sk- keys may belong to Tencent Hunyuan; choose this provider to probe only Tencent Hunyuan.",
  },
  {
    family: "qianfan",
    providerId: "qianfan",
    displayName: "Baidu Qianfan",
    prefixes: [
      { value: "bce-v3/", unique: true, confidence: "high" },
      { value: "AK-", unique: true, confidence: "medium" },
    ],
    credentialPatterns: [
      { pattern: /bce-v3\/[A-Za-z0-9_-]+\/[A-Za-z0-9_-]{16,}/i, unique: true, confidence: "high" },
    ],
    hints: ["qianfan", "baidu", "千帆", "百度", "qianfan.baidubce.com"],
    availableForChat: true,
    endpoint: "https://qianfan.baidubce.com/v2",
    modelListPath: "/models",
    defaultModels: [
      { modelId: "ernie-4.5-turbo-128k", modelDisplayName: "ERNIE 4.5 Turbo 128K", capabilities: ["chat", "reasoning", "summary"] },
      { modelId: "ernie-4.0-turbo-8k", modelDisplayName: "ERNIE 4.0 Turbo 8K", capabilities: ["chat", "reasoning", "summary"] },
      { modelId: "ernie-speed-128k", modelDisplayName: "ERNIE Speed 128K", capabilities: ["chat", "summary"] },
    ],
    reason: "Detected a Baidu Qianfan credential or platform hint. The OpenAI-compatible Qianfan endpoint can be added to the chat lane after provider confirmation.",
  },
  {
    family: "zhipu",
    providerId: "zhipu",
    displayName: "Zhipu AI",
    credentialPatterns: [
      { pattern: /[0-9a-f]{32}\.[A-Za-z0-9_-]{8,}/i, unique: true, confidence: "high" },
    ],
    hints: ["zhipu", "bigmodel", "智谱", "glm", "open.bigmodel.cn"],
    availableForChat: true,
    endpoint: "https://open.bigmodel.cn/api/paas/v4",
    modelListPath: "/models",
    defaultModels: [
      { modelId: "glm-4.5", modelDisplayName: "GLM 4.5", capabilities: ["chat", "reasoning", "coding", "summary"] },
      { modelId: "glm-4.5-air", modelDisplayName: "GLM 4.5 Air", capabilities: ["chat", "reasoning", "summary"] },
      { modelId: "glm-4-flash", modelDisplayName: "GLM 4 Flash", capabilities: ["chat", "summary"] },
    ],
    reason: "Detected a Zhipu AI key shape. The system can add GLM chat models through the OpenAI-compatible runtime adapter.",
  },
  {
    family: "xunfei-spark",
    providerId: "xunfei-spark",
    displayName: "iFlytek Spark",
    credentialPatterns: [
      { pattern: /[A-Za-z0-9_-]{12,}:[A-Za-z0-9_-]{12,}/, unique: true, confidence: "medium" },
    ],
    hints: ["xf-yun", "spark-api-open", "科大讯飞", "讯飞", "星火", "spark lite"],
    availableForChat: true,
    endpoint: "https://spark-api-open.xf-yun.com/v1",
    modelListPath: "/models",
    defaultModels: [
      { modelId: "lite", modelDisplayName: "Spark Lite", capabilities: ["chat", "summary"] },
      { modelId: "generalv3", modelDisplayName: "Spark General v3", capabilities: ["chat", "summary"] },
      { modelId: "generalv3.5", modelDisplayName: "Spark General v3.5", capabilities: ["chat", "reasoning", "summary"] },
    ],
    reason: "Detected an iFlytek Spark credential shape or platform hint. Spark OpenAI-compatible chat can be probed only after this provider is chosen.",
  },
  {
    family: "modelscope",
    providerId: "modelscope",
    displayName: "ModelScope",
    prefixes: [{ value: "ms-", unique: true, confidence: "high" }],
    hints: ["modelscope", "魔搭", "魔搭社区", "api-inference.modelscope.cn"],
    availableForChat: true,
    endpoint: "https://api-inference.modelscope.cn/v1",
    modelListPath: "/models",
    defaultModels: [
      { modelId: "Qwen/Qwen2.5-7B-Instruct", modelDisplayName: "Qwen 2.5 7B Instruct", capabilities: ["chat", "summary"] },
      { modelId: "Qwen/Qwen2.5-72B-Instruct", modelDisplayName: "Qwen 2.5 72B Instruct", capabilities: ["chat", "reasoning", "summary"] },
      { modelId: "deepseek-ai/DeepSeek-V3", modelDisplayName: "DeepSeek V3", capabilities: ["chat", "coding", "summary"] },
    ],
    reason: "Detected a ModelScope token prefix. The system can add ModelScope OpenAI-compatible chat models.",
  },
  {
    family: "cohere",
    providerId: "cohere",
    displayName: "Cohere",
    prefixes: [{ value: "sk-", unique: false, confidence: "ambiguous" }],
    hints: ["cohere", "command", "api.cohere.ai"],
    availableForChat: true,
    endpoint: "https://api.cohere.ai/compatibility/v1",
    modelListPath: "/models",
    defaultModels: [
      { modelId: "command-a-03-2025", modelDisplayName: "Command A", capabilities: ["chat", "tool-use", "summary"] },
      { modelId: "command-r-plus", modelDisplayName: "Command R Plus", capabilities: ["chat", "tool-use", "summary"] },
    ],
    reason: "Cohere exposes an OpenAI-compatible model list path. Choose Cohere to probe only Cohere instead of guessing from a generic sk- key.",
  },
  {
    family: "volcengine-doubao",
    providerId: "volcengine-doubao",
    displayName: "Volcengine Doubao / Ark",
    prefixes: [{ value: "sk-", unique: false, confidence: "ambiguous" }],
    hints: ["volcengine", "doubao", "ark.cn-beijing.volces.com", "bytedance"],
    availableForChat: true,
    endpoint: "https://ark.cn-beijing.volces.com/api/v3",
    modelListPath: "/models",
    defaultModels: [
      { modelId: "doubao-seed-1-6", modelDisplayName: "Doubao Seed", capabilities: ["chat", "vision", "summary"] },
      { modelId: "doubao-1-5-pro-32k", modelDisplayName: "Doubao 1.5 Pro", capabilities: ["chat", "reasoning", "summary"] },
    ],
    reason: "Volcengine Ark uses an OpenAI-compatible path. Choose this provider to probe Doubao models explicitly.",
  },
  {
    family: "minimax",
    providerId: "minimax",
    displayName: "MiniMax",
    prefixes: [{ value: "sk-", unique: false, confidence: "ambiguous" }],
    hints: ["minimax", "MiniMax-Text", "api.minimax.io"],
    availableForChat: true,
    endpoint: "https://api.minimax.io/v1",
    modelListPath: "/models",
    defaultModels: [
      { modelId: "MiniMax-Text-01", modelDisplayName: "MiniMax Text", capabilities: ["chat", "summary"] },
      { modelId: "abab6.5s-chat", modelDisplayName: "ABAB Chat", capabilities: ["chat", "summary"] },
    ],
    reason: "MiniMax is exposed through an OpenAI-compatible path. Choose this provider to probe MiniMax models explicitly.",
  },
  {
    family: "stepfun",
    providerId: "stepfun",
    displayName: "StepFun",
    prefixes: [{ value: "sk-", unique: false, confidence: "ambiguous" }],
    hints: ["stepfun", "step-", "api.stepfun.com"],
    availableForChat: true,
    endpoint: "https://api.stepfun.com/v1",
    modelListPath: "/models",
    defaultModels: [
      { modelId: "step-2-mini", modelDisplayName: "Step 2 Mini", capabilities: ["chat", "summary"] },
      { modelId: "step-1v-32k", modelDisplayName: "Step 1V", capabilities: ["chat", "vision", "summary"] },
    ],
    reason: "StepFun is exposed through an OpenAI-compatible path. Choose this provider to probe StepFun models explicitly.",
  },
  {
    family: "novita",
    providerId: "novita",
    displayName: "Novita AI",
    prefixes: [{ value: "sk-", unique: false, confidence: "ambiguous" }],
    hints: ["novita", "api.novita.ai"],
    availableForChat: true,
    endpoint: "https://api.novita.ai/openai/v1",
    modelListPath: "/models",
    defaultModels: [
      { modelId: "meta-llama/llama-3.1-8b-instruct", modelDisplayName: "Llama 3.1 8B", capabilities: ["chat", "summary"] },
      { modelId: "qwen/qwen-2.5-72b-instruct", modelDisplayName: "Qwen 2.5 72B", capabilities: ["chat", "reasoning", "summary"] },
    ],
    reason: "Novita AI is exposed through an OpenAI-compatible path. Choose this provider to probe Novita models explicitly.",
  },
  {
    family: "baichuan",
    providerId: "baichuan",
    displayName: "Baichuan AI",
    prefixes: [{ value: "sk-", unique: false, confidence: "ambiguous" }],
    hints: ["baichuan", "api.baichuan-ai.com"],
    availableForChat: true,
    endpoint: "https://api.baichuan-ai.com/v1",
    modelListPath: "/models",
    defaultModels: [
      { modelId: "Baichuan4", modelDisplayName: "Baichuan 4", capabilities: ["chat", "summary"] },
      { modelId: "Baichuan3-Turbo", modelDisplayName: "Baichuan 3 Turbo", capabilities: ["chat", "summary"] },
    ],
    reason: "Baichuan AI is exposed through an OpenAI-compatible path. Choose this provider to probe Baichuan models explicitly.",
  },
  {
    family: "yi",
    providerId: "yi",
    displayName: "01.AI / Yi",
    prefixes: [{ value: "sk-", unique: false, confidence: "ambiguous" }],
    hints: ["01.ai", "lingyiwanwu", "yi-large", "api.lingyiwanwu.com"],
    availableForChat: true,
    endpoint: "https://api.lingyiwanwu.com/v1",
    modelListPath: "/models",
    defaultModels: [
      { modelId: "yi-large", modelDisplayName: "Yi Large", capabilities: ["chat", "summary"] },
      { modelId: "yi-vision", modelDisplayName: "Yi Vision", capabilities: ["chat", "vision", "summary"] },
    ],
    reason: "01.AI / Yi is exposed through an OpenAI-compatible path. Choose this provider to probe Yi models explicitly.",
  },
  {
    family: "infini-ai",
    providerId: "infini-ai",
    displayName: "Infini AI",
    prefixes: [{ value: "sk-", unique: false, confidence: "ambiguous" }],
    hints: ["infini", "cloud.infini-ai.com"],
    availableForChat: true,
    endpoint: "https://cloud.infini-ai.com/maas/v1",
    modelListPath: "/models",
    defaultModels: [
      { modelId: "qwen2.5-72b-instruct", modelDisplayName: "Qwen 2.5 72B Instruct", capabilities: ["chat", "summary"] },
      { modelId: "bge-m3", modelDisplayName: "BGE M3", capabilities: ["embedding"] },
    ],
    reason: "Infini AI is exposed through an OpenAI-compatible path. Choose this provider to probe Infini AI models explicitly.",
  },
  {
    family: "cloudflare-workers-ai",
    providerId: "cloudflare-workers-ai",
    displayName: "Cloudflare Workers AI",
    prefixes: [{ value: "cfat_", unique: true, confidence: "high" }],
    hints: ["cloudflare", "workers ai", "api.cloudflare.com/client/v4/accounts"],
    availableForChat: false,
    defaultModels: [
      { modelId: "@cf/meta/llama-3.1-8b-instruct", modelDisplayName: "Llama 3.1 8B Instruct", capabilities: ["chat", "summary"] },
      { modelId: "@cf/qwen/qwen1.5-14b-chat-awq", modelDisplayName: "Qwen Chat", capabilities: ["chat", "summary"] },
      { modelId: "@cf/baai/bge-base-en-v1.5", modelDisplayName: "BGE Base Embedding", capabilities: ["embedding"] },
    ],
    reason: "Detected a Cloudflare API token. Cloudflare Workers AI also needs an account-specific endpoint, so it is recognized but not one-click chat-enabled yet.",
  },
  {
    family: "huggingface",
    providerId: "huggingface",
    displayName: "Hugging Face Router",
    prefixes: [{ value: "hf_", unique: true, confidence: "high" }],
    hints: ["huggingface", "bloom", "hf_", "router.huggingface.co"],
    availableForChat: true,
    endpoint: "https://router.huggingface.co/v1",
    modelListPath: "/models",
    defaultModels: [
      { modelId: "openai/gpt-oss-20b", modelDisplayName: "GPT OSS 20B", capabilities: ["chat", "summary"] },
      { modelId: "Qwen/Qwen2.5-7B-Instruct", modelDisplayName: "Qwen 2.5 7B Instruct", capabilities: ["chat", "summary"] },
      { modelId: "bigscience/bloom", modelDisplayName: "BLOOM", capabilities: ["chat", "summary"] },
    ],
    reason: "Detected a Hugging Face token. The system can probe the Hugging Face Router OpenAI-compatible model list.",
  },
  {
    family: "coze",
    providerId: "coze",
    displayName: "Coze",
    prefixes: [{ value: "pat_", unique: true, confidence: "high" }],
    hints: ["coze", "扣子"],
    availableForChat: false,
    defaultModels: [
      { modelId: "coze-bot-api", modelDisplayName: "Coze Bot API", capabilities: ["chat", "tool-use"] },
      { modelId: "coze-workflow-api", modelDisplayName: "Coze Workflow API", capabilities: ["tool-use"] },
    ],
    reason: "Detected a Coze token. Coze is an agent/workflow platform, not a current OpenAI-compatible chat provider in this runtime.",
  },
  {
    family: "generic-openai-compatible",
    providerId: "generic-openai-compatible",
    displayName: "Generic OpenAI-Compatible API",
    prefixes: [{ value: "sk-", unique: false, confidence: "ambiguous" }],
    hints: ["公益api", "free api", "openai兼容", "openai-compatible", "oneapi", "newapi"],
    availableForChat: true,
    endpointRequired: true,
    defaultModels: [
      { modelId: "custom-chat-model", modelDisplayName: "Custom Chat Model", capabilities: ["chat", "summary"] },
    ],
    reason: "Detected a generic OpenAI-compatible key and base URL. The system can add it as a custom chat provider after a real /chat probe.",
  },
  {
    family: "gemini",
    providerId: "gemini",
    displayName: "Gemini",
    prefixes: [{ value: "AIza", unique: true, confidence: "high" }],
    availableForChat: false,
    endpoint: "https://generativelanguage.googleapis.com/v1beta",
    modelListPath: "/models",
    modelListAuth: "gemini-query-key",
    defaultModels: [
      { modelId: "gemini-embedding-001", modelDisplayName: "Gemini Embedding 001", capabilities: ["embedding"] },
      { modelId: "gemini-2.5-flash", modelDisplayName: "Gemini 2.5 Flash", capabilities: ["chat", "vision", "coding", "reasoning", "summary"] },
      { modelId: "gemini-2.5-pro", modelDisplayName: "Gemini 2.5 Pro", capabilities: ["chat", "vision", "coding", "reasoning", "summary"] },
      { modelId: "imagen-4.0-generate-001", modelDisplayName: "Imagen 4", capabilities: ["image-generation"] },
      { modelId: "veo-3.0-generate-001", modelDisplayName: "Veo 3", capabilities: ["video-generation"] },
    ],
    reason: "Detected a Gemini key. Gemini is currently wired for embedding/vector infrastructure, not the chat provider lane.",
  },
  {
    family: "anthropic",
    providerId: "anthropic",
    displayName: "Anthropic",
    prefixes: [{ value: "sk-ant-", unique: true, confidence: "high" }],
    availableForChat: false,
    endpoint: "https://api.anthropic.com/v1",
    modelListPath: "/models",
    modelListAuth: "anthropic-api-key",
    defaultModels: [
      { modelId: "claude-sonnet-4.5", modelDisplayName: "Claude Sonnet 4.5", capabilities: ["chat", "vision", "coding", "reasoning", "tool-use", "summary"] },
      { modelId: "claude-3-5-sonnet-latest", modelDisplayName: "Claude 3.5 Sonnet Latest", capabilities: ["chat", "vision", "coding", "reasoning", "tool-use", "summary"] },
    ],
    reason: "Detected an Anthropic key. The current chat lane only supports existing OpenAI-compatible adapters, so native Anthropic is recognized but not one-click chat-enabled yet.",
  },
];
