/**
 * Provider probe catalog — static configuration for every known provider.
 *
 * Extracted from providerProbeRegistry.js to keep that module under 500 lines.
 */

export const MODEL_IMPORT_SOURCE = "provider_models_api";
export const MODEL_IMPORT_TIMEOUT_MS = 4_000;

export const PROVIDER_PROBES = {
  nvidia: {
    providerId: "nvidia",
    displayName: "NVIDIA",
    baseUrl: "https://integrate.api.nvidia.com/v1",
    modelsPath: "/models",
    auth: "bearer",
    defaultCapabilities: ["chat", "summary"],
  },
  openai: {
    providerId: "openai",
    displayName: "OpenAI",
    baseUrl: "https://api.openai.com/v1",
    modelsPath: "/models",
    auth: "bearer",
    defaultCapabilities: ["chat", "summary"],
  },
  openrouter: {
    providerId: "openrouter",
    displayName: "OpenRouter",
    baseUrl: "https://openrouter.ai/api/v1",
    modelsPath: "/models?output_modalities=all",
    auth: "bearer",
    defaultCapabilities: ["chat", "summary"],
    providerGroup: "openai-compatible",
  },
  dashscope: {
    providerId: "dashscope",
    displayName: "DashScope",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    modelsPath: "/models",
    auth: "bearer",
    defaultCapabilities: ["chat", "summary"],
    providerGroup: "openai-compatible",
  },
  deepseek: {
    providerId: "deepseek",
    displayName: "DeepSeek",
    baseUrl: "https://api.deepseek.com/v1",
    modelsPath: "/models",
    auth: "bearer",
    defaultCapabilities: ["chat", "coding", "summary"],
    providerGroup: "openai-compatible",
  },
  groq: {
    providerId: "groq",
    displayName: "Groq",
    baseUrl: "https://api.groq.com/openai/v1",
    modelsPath: "/models",
    auth: "bearer",
    defaultCapabilities: ["chat", "summary"],
    providerGroup: "openai-compatible",
  },
  together: {
    providerId: "together",
    displayName: "Together AI",
    baseUrl: "https://api.together.xyz/v1",
    modelsPath: "/models",
    auth: "bearer",
    defaultCapabilities: ["chat", "summary"],
    providerGroup: "openai-compatible",
  },
  mistral: {
    providerId: "mistral",
    displayName: "Mistral",
    baseUrl: "https://api.mistral.ai/v1",
    modelsPath: "/models",
    auth: "bearer",
    defaultCapabilities: ["chat", "summary"],
    providerGroup: "openai-compatible",
  },
  xai: {
    providerId: "xai",
    displayName: "xAI",
    baseUrl: "https://api.x.ai/v1",
    modelsPath: "/models",
    auth: "bearer",
    defaultCapabilities: ["chat", "reasoning", "summary"],
    providerGroup: "openai-compatible",
  },
  perplexity: {
    providerId: "perplexity",
    displayName: "Perplexity",
    baseUrl: "https://api.perplexity.ai",
    modelsPath: "/models",
    auth: "bearer",
    defaultCapabilities: ["chat", "summary"],
    providerGroup: "openai-compatible",
  },
  fireworks: {
    providerId: "fireworks",
    displayName: "Fireworks AI",
    baseUrl: "https://api.fireworks.ai/inference/v1",
    modelsPath: "/models",
    auth: "bearer",
    defaultCapabilities: ["chat", "summary"],
    providerGroup: "openai-compatible",
  },
  cerebras: {
    providerId: "cerebras",
    displayName: "Cerebras",
    baseUrl: "https://api.cerebras.ai/v1",
    modelsPath: "/models",
    auth: "bearer",
    defaultCapabilities: ["chat", "summary"],
    providerGroup: "openai-compatible",
  },
  moonshot: {
    providerId: "moonshot",
    displayName: "Moonshot AI",
    baseUrl: "https://api.moonshot.ai/v1",
    modelsPath: "/models",
    auth: "bearer",
    defaultCapabilities: ["chat", "coding", "summary"],
    providerGroup: "openai-compatible",
  },
  siliconflow: {
    providerId: "siliconflow",
    displayName: "SiliconFlow",
    baseUrl: "https://api.siliconflow.cn/v1",
    modelsPath: "/models",
    auth: "bearer",
    defaultCapabilities: ["chat", "summary"],
    providerGroup: "openai-compatible",
  },
  "tencent-hunyuan": {
    providerId: "tencent-hunyuan",
    displayName: "Tencent Hunyuan",
    baseUrl: "https://api.hunyuan.cloud.tencent.com/v1",
    modelsPath: "/models",
    auth: "bearer",
    defaultCapabilities: ["chat", "summary"],
    providerGroup: "openai-compatible",
  },
  qianfan: {
    providerId: "qianfan",
    displayName: "Baidu Qianfan",
    baseUrl: "https://qianfan.baidubce.com/v2",
    modelsPath: "/models",
    auth: "bearer",
    defaultCapabilities: ["chat", "summary"],
    providerGroup: "openai-compatible",
  },
  zhipu: {
    providerId: "zhipu",
    displayName: "Zhipu AI",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    modelsPath: "/models",
    auth: "bearer",
    defaultCapabilities: ["chat", "reasoning", "coding", "summary"],
    providerGroup: "openai-compatible",
  },
  "xunfei-spark": {
    providerId: "xunfei-spark",
    displayName: "iFlytek Spark",
    baseUrl: "https://spark-api-open.xf-yun.com/v1",
    modelsPath: "/models",
    auth: "bearer",
    defaultCapabilities: ["chat", "summary"],
    providerGroup: "openai-compatible",
  },
  modelscope: {
    providerId: "modelscope",
    displayName: "ModelScope",
    baseUrl: "https://api-inference.modelscope.cn/v1",
    modelsPath: "/models",
    auth: "bearer",
    defaultCapabilities: ["chat", "summary"],
    providerGroup: "openai-compatible",
  },
  cohere: {
    providerId: "cohere",
    displayName: "Cohere",
    baseUrl: "https://api.cohere.ai/compatibility/v1",
    modelsPath: "/models",
    auth: "bearer",
    defaultCapabilities: ["chat", "tool-use", "summary"],
    providerGroup: "openai-compatible",
  },
  "volcengine-doubao": {
    providerId: "volcengine-doubao",
    displayName: "Volcengine Doubao / Ark",
    baseUrl: "https://ark.cn-beijing.volces.com/api/v3",
    modelsPath: "/models",
    auth: "bearer",
    defaultCapabilities: ["chat", "vision", "coding", "reasoning"],
    providerGroup: "openai-compatible",
  },
  minimax: {
    providerId: "minimax",
    displayName: "MiniMax",
    baseUrl: "https://api.minimax.io/v1",
    modelsPath: "/models",
    auth: "bearer",
    defaultCapabilities: ["chat", "vision", "tool-use"],
    providerGroup: "openai-compatible",
  },
  stepfun: {
    providerId: "stepfun",
    displayName: "StepFun",
    baseUrl: "https://api.stepfun.com/v1",
    modelsPath: "/models",
    auth: "bearer",
    defaultCapabilities: ["chat", "vision", "coding"],
    providerGroup: "openai-compatible",
  },
  novita: {
    providerId: "novita",
    displayName: "Novita AI",
    baseUrl: "https://api.novita.ai/openai/v1",
    modelsPath: "/models",
    auth: "bearer",
    defaultCapabilities: ["chat", "vision", "image", "coding"],
    providerGroup: "openai-compatible",
  },
  baichuan: {
    providerId: "baichuan",
    displayName: "Baichuan AI",
    baseUrl: "https://api.baichuan-ai.com/v1",
    modelsPath: "/models",
    auth: "bearer",
    defaultCapabilities: ["chat", "coding"],
    providerGroup: "openai-compatible",
  },
  yi: {
    providerId: "yi",
    displayName: "01.AI / Yi",
    baseUrl: "https://api.lingyiwanwu.com/v1",
    modelsPath: "/models",
    auth: "bearer",
    defaultCapabilities: ["chat", "vision", "coding"],
    providerGroup: "openai-compatible",
  },
  "infini-ai": {
    providerId: "infini-ai",
    displayName: "Infini AI",
    baseUrl: "https://cloud.infini-ai.com/maas/v1",
    modelsPath: "/models",
    auth: "bearer",
    defaultCapabilities: ["chat", "embedding", "rerank"],
    providerGroup: "openai-compatible",
  },
  huggingface: {
    providerId: "huggingface",
    displayName: "Hugging Face Router",
    baseUrl: "https://router.huggingface.co/v1",
    modelsPath: "/models",
    auth: "bearer",
    defaultCapabilities: ["chat", "vision", "coding", "image"],
    providerGroup: "openai-compatible",
  },
  mimo: {
    providerId: "mimo",
    displayName: "MiMo Token Plan",
    baseUrl: "https://token-plan-cn.xiaomimimo.com/v1",
    modelsPath: "/models",
    auth: "bearer",
    defaultCapabilities: ["chat", "reasoning", "summary"],
    providerGroup: "openai-compatible",
  },
  anthropic: {
    providerId: "anthropic",
    displayName: "Anthropic Claude",
    baseUrl: "https://api.anthropic.com/v1",
    modelsPath: "/models",
    auth: "anthropic-api-key",
    defaultCapabilities: ["native-chat", "vision", "coding", "reasoning", "tool-use"],
    providerGroup: "native",
  },
  "openai-compatible": {
    providerId: "openai-compatible",
    displayName: "OpenAI-Compatible",
    modelsPath: "/models",
    auth: "bearer",
    defaultCapabilities: ["chat", "summary"],
    requiresBaseUrl: true,
    providerGroup: "openai-compatible",
  },
  gemini: {
    providerId: "gemini",
    displayName: "Gemini",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    modelsPath: "/models",
    auth: "query-key",
    defaultCapabilities: ["chat", "summary"],
  },
};

export function getProviderProbeConfig(providerId) {
  return PROVIDER_PROBES[providerId] ?? null;
}

export function listModelImportProviders() {
  return Object.values(PROVIDER_PROBES).map((config) => ({
    providerId: config.providerId,
    displayName: config.displayName,
    providerGroup: config.providerGroup ?? config.providerId,
    baseUrl: config.requiresBaseUrl ? null : config.baseUrl,
    requiresBaseUrl: Boolean(config.requiresBaseUrl),
    modelsPath: config.modelsPath,
    auth: config.auth,
    defaultCapabilities: [...(config.defaultCapabilities ?? [])],
  }));
}
