const PROVIDER_DISPATCH_HTTP_STATUS = new Map<string, number>([
  ["PROVIDER_DISPATCH_KEY_REQUIRED", 400],
  ["PROVIDER_DISPATCH_KEY_INVALID", 400],
  ["PROVIDER_DISPATCH_INPUT_INVALID", 400],
  ["PROVIDER_DISPATCH_ALREADY_RESERVED", 409],
  ["PROVIDER_DISPATCH_KEY_REUSED", 409],
  ["PROVIDER_DISPATCH_RESERVATION_UNCONFIRMED", 409],
  ["PROVIDER_DISPATCH_STORE_UNAVAILABLE", 503],
  ["PROVIDER_DISPATCH_CAPACITY_REACHED", 503],
  ["PROVIDER_DISPATCH_GATE_UNAVAILABLE", 503],
]);

export function resolveProviderDispatchHttpStatus(code: unknown): number | null {
  return PROVIDER_DISPATCH_HTTP_STATUS.get(String(code ?? "").trim().toUpperCase()) ?? null;
}
