export function buildCodexPromptPack({ task, relevantFiles, tokenBudgetReport, freshnessReport }) {
  const lines = [
    "# Codex Prompt Pack",
    "",
    "## Task",
    task,
    "",
    "## Boundaries",
    "- Do not modify legacy/.",
    "- Do not read or print .env, API keys, tokens, secrets, credentials, or webhooks.",
    "- Do not call OpenAI, Claude, OpenRouter, MiMo, NVIDIA, or any provider.",
    "- Do not modify /chat or /chat-gateway/execute.",
    "- Do not modify Codex config or real base_url.",
    "- Do not deploy, release, tag, or upload artifacts.",
    "- Do not claim workspace clean.",
    "",
    "## Relevant Files",
    ...relevantFiles.map((item) => `- ${item.path} (${item.mode}): ${item.reason}`),
    "",
    "## Token Budget",
    `- budgetName: ${tokenBudgetReport.budget.budgetName}`,
    `- maxTokens: ${tokenBudgetReport.budget.maxTokens}`,
    `- estimatedTokens: ${tokenBudgetReport.budget.estimatedTokens}`,
    `- respected: ${tokenBudgetReport.budget.respected}`,
    "",
    "## Freshness",
    `- contextHash: ${freshnessReport.currentHash}`,
    `- stale: ${freshnessReport.stale}`,
    `- staleContextDetectedWhenExpected: ${freshnessReport.staleContextDetectedWhenExpected}`,
    "",
    "## Verification Commands",
    "- pnpm -r --if-present check",
    "- node --check tools/phase592a/validate-phase592a-codex-context-gateway-architecture.mjs",
    "- pnpm verify:phase592a-t-codex-context-gateway-token-budget-manager",
    "- pnpm verify:phase107a-secret-safety",
    "- pnpm verify:phase321a-workbench-product-recovery",
    "- pnpm sync:readme-agents-current-state",
    "- pnpm verify:phase306c-readme-agents-auto-sync-guard",
    "",
  ];
  return {
    completed: true,
    markdown: lines.join("\n"),
  };
}
