export const codexContextGatewayCopy = Object.freeze({
  title: "Codex Context Gateway",
  subtitle: "Operator preview panel for generated context packs. It is not a real Codex connection.",
  boundaryBadges: [
    "no provider call",
    "no secret read",
    "no webhook read",
    "no Codex base_url change",
    "no /chat change",
    "no deploy / release",
    "preview only",
  ],
  actions: [
    ["context-pack", "View Context Pack"],
    ["token-budget", "View Token Budget"],
    ["relevant-files", "View Relevant Files"],
    ["prompt-pack", "View Prompt Pack"],
    ["freshness", "View Freshness"],
    ["evidence-index", "View Evidence Index"],
    ["copy-prompt", "Copy Prompt Preview"],
    ["refresh-preview", "Refresh Preview"],
    ["usage-workflow", "Usage Workflow"],
    ["preflight", "Preflight"],
    ["validation-plan", "Validation Plan"],
    ["dry-run-wrapper", "Dry-run Wrapper"],
    ["failure-modes", "Failure Modes"],
    ["operator-checklist", "Operator Checklist"],
    ["usage-trial", "Usage Trial"],
    ["next-instruction", "Next Instruction"],
    ["repeated-benchmark", "Repeated Benchmark"],
    ["benchmark-next", "Benchmark Next Step"],
    ["base-url-design", "Base URL Design"],
    ["base-url-config-preview", "Config Preview"],
    ["base-url-authorization", "Authorization Gate"],
    ["base-url-rollback", "Rollback Plan"],
    ["base-url-risk-review", "Risk Review"],
    ["base-url-checklist", "Integration Checklist"],
    ["auth-status", "Auth Status"],
    ["auth-missing-fields", "Missing Fields"],
    ["auth-dry-run-simulation", "Dry-run Simulation"],
    ["auth-redacted-config", "Redacted Config"],
    ["auth-relay", "Relay Simulation"],
    ["auth-account-pool", "Account Pool"],
    ["auth-credential", "CredentialRef"],
    ["auth-policy", "Dry-run Policy"],
    ["auth-rollback", "Rollback Simulation"],
    ["auth-emergency", "Emergency Disable"],
    ["auth-evidence", "Authorization Evidence"],
    ["human-approval-review", "Human Approval"],
    ["human-approval-missing-fields", "Approval Missing Fields"],
    ["guarded-real-test-readiness", "Guarded Test Readiness"],
    ["phase600-readiness", "Phase600 Readiness"],
    ["phase600-missing-fields", "Phase600 Missing Fields"],
    ["phase600-next-action", "Phase600 Next Action"],
    ["phase601-preparation", "Phase601 Preparation"],
    ["phase601-command-bundle", "Phase601 Command Bundle"],
    ["phase602-one-shot-result", "Phase602 One-Shot Result"],
    ["phase602-cleanup", "Phase602 Cleanup"],
    ["phase603-custom-provider-route", "Phase603 Provider Route"],
    ["phase603-command-bundle", "Phase603 Command Bundle"],
    ["phase604-custom-provider-result", "Phase604 Provider Result"],
    ["phase604-cleanup", "Phase604 Cleanup"],
    ["phase610r-codex-exec-result", "Phase610R Exec Result"],
    ["phase610r-boundary", "Phase610R Boundary"],
    ["phase611r-reliability-design", "Phase611R Reliability"],
    ["phase611r-attempt-plan", "Phase611R Attempt Plan"],
    ["phase611r-guarded-test-design", "Phase611R Guarded Design"],
    ["phase611r-phase612-gate", "Phase612 Gate"],
    ["phase612r-repeated-result", "Phase612R Result"],
    ["phase612r-repeated-boundary", "Phase612R Boundary"],
    ["phase613r-closure", "Phase613R Closure"],
    ["phase613r-next-gate", "Phase613R Next Gate"],
    ["phase614r-preview-gate", "Phase614R Preview Gate"],
    ["phase614r-route-contract", "Phase614R Route Contract"],
    ["phase615r-approval-packet", "Phase615R Approval"],
    ["phase615r-operator-checklist", "Phase615R Checklist"],
    ["phase616r-620r-dry-run-candidate", "Phase616R-620R Dry-Run"],
    ["phase616r-620r-route-contract", "Phase616R-620R Contract"],
    ["phase621r-628r-isolated-candidate", "Phase621R-628R Candidate"],
    ["phase621r-628r-reliability", "Phase621R-628R Reliability"],
    ["phase629r-final-approval", "Phase629R Approval"],
    ["phase629r-go-no-go", "Phase629R Go/No-Go"],
    ["phase630r-design-patch", "Phase630R Design"],
    ["phase630r-route-preview", "Phase630R Route Preview"],
    ["phase639r-p1-approval-preview", "Phase639R P1 Approval"],
    ["phase639r-nightly-fallback-panel", "Phase639R Nightly Fallback"],
    ["phase640r-nightly-retry-pack", "Phase640R Nightly Retry Pack"],
    ["phase641r-nightly-registration-intake", "Phase641R Nightly Intake"],
    ["phase640r-external-tool-mode", "External Tool Mode"],
    ["phase641r-645r-external-tool-bundle", "External Tool Bundle"],
    ["phase646r-650r-external-tool-dashboard", "Daily Workflow Dashboard"],
  ],
});
