function renderGate(gate) {
  return gate ? `${gate.workflowName} ${gate.status} ${gate.conclusion}`.trim() : "none";
}

export function renderReleasePublishPreflightEvidence(evidence) {
  const headGate = evidence.github.latestHeadReleaseGate;
  const targetGate = evidence.github.releaseTargetGate;
  return [
    "# Phase 135A Release Publish Preflight Evidence",
    "",
    `- Phase: ${evidence.phase}`,
    `- Status: ${evidence.status}`,
    `- Generated at: ${evidence.generatedAt}`,
    `- Candidate version: ${evidence.candidate.version}`,
    `- Candidate tag: ${evidence.candidate.tag}`,
    `- Candidate title: ${evidence.candidate.title}`,
    `- Release target commit: ${evidence.candidate.releaseTargetCommit}`,
    `- Release URL: ${evidence.candidate.releaseUrl}`,
    `- Release draft: ${evidence.github.release.isDraft}`,
    `- Release prerelease: ${evidence.github.release.isPrerelease}`,
    `- Release published at: ${evidence.github.release.publishedAt ?? "none"}`,
    `- Release asset count: ${evidence.github.release.assetCount}`,
    `- Release published by later Phase136A: ${evidence.safety.releasePublishedByLaterPhase136}`,
    `- Current head: ${evidence.git.headSha}`,
    `- Current head Release Gate: ${renderGate(headGate)}`,
    `- Current head Release Gate URL: ${headGate?.url ?? "none"}`,
    `- Release target gate: ${renderGate(targetGate)}`,
    `- Release target gate URL: ${targetGate?.url ?? "none"}`,
    `- Required publish phrase: ${evidence.candidate.requiredPublishPhrase}`,
    `- Required asset phrase: ${evidence.candidate.requiredAssetPhrase}`,
    `- Release published by this phase: ${evidence.safety.releasePublished}`,
    `- Release artifact uploaded by this phase: ${evidence.safety.releaseArtifactUploaded}`,
    `- Package published: ${evidence.safety.packagePublished}`,
    `- Docker image published: ${evidence.safety.dockerImagePublished}`,
    `- Cloud deployment complete: ${evidence.safety.cloudDeploymentComplete}`,
    `- Global release complete: ${evidence.safety.globalReleaseComplete}`,
    `- Plain secret findings: ${evidence.secretFindingCount}`,
    `- Conclusion: ${evidence.conclusion}`,
    "",
    "## Checks",
    "",
    ...Object.entries(evidence.checks).map(
      ([name, value]) => `- ${name}: ${value ? "passed" : "failed"}`,
    ),
    "",
    "## Next Manual Decisions",
    "",
    ...evidence.nextManualDecisions.map((decision) => `- ${decision}`),
    "",
    "## Boundary",
    "",
    "- This phase is a read-only publish and asset-upload preflight.",
    "- It does not publish the draft release, upload assets, publish packages/images, deploy cloud infrastructure, or complete global release.",
    "",
  ].join("\n");
}

export function renderReleasePublishExecutionEvidence(evidence) {
  const headGate = evidence.github.latestHeadReleaseGate;
  const targetGate = evidence.github.releaseTargetGate;
  return [
    "# Phase 136A Release Publish Execution Evidence",
    "",
    `- Phase: ${evidence.phase}`,
    `- Status: ${evidence.status}`,
    `- Generated at: ${evidence.generatedAt}`,
    `- Candidate version: ${evidence.candidate.version}`,
    `- Candidate tag: ${evidence.candidate.tag}`,
    `- Candidate title: ${evidence.candidate.title}`,
    `- Release target commit: ${evidence.candidate.releaseTargetCommit}`,
    `- Release URL: ${evidence.candidate.releaseUrl}`,
    `- Release published at: ${evidence.candidate.releasePublishedAt}`,
    `- Release draft: ${evidence.github.release.isDraft}`,
    `- Release prerelease: ${evidence.github.release.isPrerelease}`,
    `- Release asset count: ${evidence.github.release.assetCount}`,
    `- Current head Release Gate: ${renderGate(headGate)}`,
    `- Current head Release Gate URL: ${headGate?.url ?? "none"}`,
    `- Release target gate: ${renderGate(targetGate)}`,
    `- Release target gate URL: ${targetGate?.url ?? "none"}`,
    `- Release published by this phase: ${evidence.safety.releasePublished}`,
    `- Release currently draft by later Phase137A: ${evidence.safety.releaseCurrentlyDraftByLaterPhase137}`,
    `- Release rolled back by later Phase137A: ${evidence.safety.releaseRolledBackByLaterPhase137}`,
    `- Release artifact uploaded by this phase: ${evidence.safety.releaseArtifactUploaded}`,
    `- Package published: ${evidence.safety.packagePublished}`,
    `- Docker image published: ${evidence.safety.dockerImagePublished}`,
    `- Cloud deployment complete: ${evidence.safety.cloudDeploymentComplete}`,
    `- Global release complete: ${evidence.safety.globalReleaseComplete}`,
    `- Plain secret findings: ${evidence.secretFindingCount}`,
    `- Conclusion: ${evidence.conclusion}`,
    "",
    "## Checks",
    "",
    ...Object.entries(evidence.checks).map(
      ([name, value]) => `- ${name}: ${value ? "passed" : "failed"}`,
    ),
    "",
    "## Remaining Limits",
    "",
    ...evidence.remainingLimits.map((limit) => `- ${limit}`),
    "",
    "## Boundary",
    "",
    "- This phase publishes the existing GitHub prerelease only.",
    "- It does not upload assets, publish packages/images, deploy cloud infrastructure, or complete global release.",
    "",
  ].join("\n");
}
