import { verifyCodexOneShotReadinessPhase } from "./verifyCodexOneShotReadinessSupport.js";

await verifyCodexOneShotReadinessPhase({
  phase: "phase-264a-codex-one-shot-operator-manual",
  docPath: "docs/CODEX_ONE_SHOT_OPERATOR_MANUAL.md",
  verifierPath: "apps/ai-gateway-service/src/entrypoints/verifyCodexOneShotOperatorManual.js",
  rootScriptName: "verify:phase264a-codex-one-shot-operator-manual",
  serviceScriptValue: "node ./src/entrypoints/verifyCodexOneShotOperatorManual.js",
  requiredDocSections: [
    "# Codex One-shot Operator Manual",
    "## 1. When To Consider One-shot",
    "## 2. When Not To Consider One-shot",
    "## 3. Classify The Task",
    "## 4. Run Preflight",
    "## 5. Generate Approval-preview",
    "## 6. Generate Dry-run Execution Plan",
    "## 7. Receive Codex Result",
    "## 8. Review Evidence",
    "## 9. Trigger Stop Rules",
    "## 10. Go / No-go Judgment",
    "## 11. Current No-real-execution Boundary",
    "## 12. Future Missing Pieces",
  ],
  requiredDocMarkers: [
    "Consider one-shot readiness only",
    "Do not consider one-shot",
    "Classify as safe-preview, needs-human-review, blocked, or forbidden.",
    "Run preflight",
    "approval-preview is not execution permission",
    "dry-run plan",
    "modified files, executed commands, verification, evidence paths, boundary review, and A-M summary",
    "Failed evidence is not sealed.",
    "Trigger stop rules",
    "Go/no-go means readiness only.",
    "executionEnabled=false",
    "codexExecInvoked=false",
  ],
  requiredUiMarkers: [
    "phase264a-codex-one-shot-operator-manual",
    "when to consider",
    "when forbidden",
    "classify task",
    "run preflight",
    "approval-preview",
    "dry-run plan",
    "result intake",
    "stop rules",
    "go/no-go",
    "no real execution",
  ],
  requiredVerificationCommands: [
    "cmd /c pnpm run verify:phase264a-codex-one-shot-operator-manual",
  ],
  requiredEvidenceStatusPaths: [
    "apps/ai-gateway-service/evidence/phase-263a-codex-one-shot-ui-readiness-panel.json",
  ],
  conclusionPassed: "codex-one-shot-operator-manual-preview-ready",
  conclusionFailed: "codex-one-shot-operator-manual-preview-incomplete",
  capabilityList: [
    "one-shot-operator-manual",
    "classification-flow",
    "preflight-flow",
    "approval-preview-flow",
    "dry-run-plan-flow",
    "stop-rules-flow",
  ],
  notes: [
    "Phase 264A consolidates Phases 256A-263A into a readiness manual.",
    "It does not enable real Codex execution.",
  ],
});
