import { verifyPersonalValuePhase } from "./verifyPersonalValueClosureSupport.js";

await verifyPersonalValuePhase({
  phase: "phase-242a-personal-action-queue",
  docPath: "docs/PERSONAL_ACTION_QUEUE.md",
  verifierPath: "apps/ai-gateway-service/src/entrypoints/verifyPersonalActionQueue.js",
  rootScriptName: "verify:phase242a-personal-action-queue",
  serviceScriptValue: "node ./src/entrypoints/verifyPersonalActionQueue.js",
  requiredDocSections: [
    "# Personal Action Queue",
    "## 2. Task Queue Format",
    "## 3. Required Task Fields",
    "## 4. Generating The Next Task From Decision Dashboard",
    "## 5. Avoiding Infinite Expansion",
    "## 6. Handling Blocked / Skipped / Done",
    "## 7. Recording Commercialization Pause",
    "## 8. Recording No Real Execution",
  ],
  requiredDocMarkers: [
    "taskId",
    "title",
    "why now",
    "allowed scope",
    "blocked scope",
    "Codex-ready or not",
    "required verification",
    "expected evidence",
    "stop condition",
    "commercialization paused",
    "no real execution",
  ],
  requiredUiMarkers: [
    "phase242a-personal-action-queue",
    "Next task",
    "Why now",
    "Ready for Codex",
    "Verification required",
    "Stop condition",
  ],
  requiredVerificationCommands: [
    "cmd /c pnpm run verify:phase242a-personal-action-queue",
    "cmd /c pnpm run verify:phase241a-personal-live-trial",
    "cmd /c pnpm run verify:phase240a-personal-decision-dashboard",
    "cmd /c pnpm run verify:phase239a-personal-project-knowledge-pack",
    "cmd /c pnpm run verify:phase238a-personal-daily-workflow",
    "cmd /c pnpm run verify:phase237a-personal-operator-console",
    "cmd /c pnpm run verify:phase199a-real-ui-trial-runtime-sync",
    "cmd /c pnpm run verify:phase107a-secret-safety",
    "cmd /c pnpm run verify:phase105a-user-journey",
    "cmd /c pnpm run health:phase12a",
    "cmd /c pnpm run doctor:phase13a",
    "cmd /c pnpm -r --if-present check",
  ],
  requiredEvidenceStatusPaths: [
    "apps/ai-gateway-service/evidence/phase-241a-personal-live-trial.json",
  ],
  conclusionPassed: "personal-action-queue-preview-ready",
  conclusionFailed: "personal-action-queue-incomplete",
  capabilityList: [
    "task-queue-format",
    "decision-dashboard-to-next-task",
    "blocked-skipped-done-status",
    "commercialization-pause-record",
    "no-real-execution-record",
  ],
  notes: [
    "Phase 242A defines a preview-only personal action queue.",
    "The queue records next task, why now, Codex readiness, required verification, evidence, and stop condition.",
    "No real execution, worktree, workflow runner, automatic commit/push, or new dependency is added.",
  ],
});
