import { verifyPersonalValuePhase } from "./verifyPersonalValueClosureSupport.js";

await verifyPersonalValuePhase({
  phase: "phase-245a-personal-value-closure",
  docPath: "docs/PERSONAL_VALUE_CLOSURE_SNAPSHOT.md",
  verifierPath: "apps/ai-gateway-service/src/entrypoints/verifyPersonalValueClosureSnapshot.js",
  rootScriptName: "verify:phase245a-personal-value-closure",
  serviceScriptValue: "node ./src/entrypoints/verifyPersonalValueClosureSnapshot.js",
  requiredDocSections: [
    "# Personal Value Closure Snapshot",
    "## 1. Final Self-use Value Conclusion",
    "## 2. Completed Capability List",
    "## 3. Actual Value For The Operator",
    "## 4. Current Cannot-do List",
    "## 5. Daily Entry Point",
    "## 6. Common Verification Commands",
    "## 7. Evidence Index",
    "## 8. Next Optional Routes",
    "## 9. Recommended Next Route",
    "## 10. Final Boundary Statement",
  ],
  requiredDocMarkers: [
    "Personal Operator Console",
    "Daily Workflow",
    "Project Knowledge Pack",
    "Decision Dashboard",
    "Live Trial",
    "Action Queue",
    "Review & Evidence Loop",
    "Final Operator Manual",
    "Option A: Continue self-use UI polish",
    "Option B: Start real knowledge-base import experience",
    "Option C: Start controlled Codex one-shot readiness",
    "Option D: Return to commercial demo pack",
    "Recommended next route: Option B",
    "Do not automatically enter Option B",
  ],
  requiredUiMarkers: [
    "phase245a-personal-value-closure",
    "Self-use baseline sealed",
    "What it helps me do",
    "What it will not do",
    "Next decision gate",
  ],
  requiredVerificationCommands: [
    "cmd /c pnpm run verify:phase245a-personal-value-closure",
    "cmd /c pnpm run verify:phase244a-personal-operator-manual-final",
    "cmd /c pnpm run verify:phase243a-personal-review-evidence-loop",
    "cmd /c pnpm run verify:phase242a-personal-action-queue",
    "cmd /c pnpm run verify:phase241a-personal-live-trial",
    "cmd /c pnpm run verify:phase240a-personal-decision-dashboard",
    "cmd /c pnpm run verify:phase239a-personal-project-knowledge-pack",
    "cmd /c pnpm run verify:phase238a-personal-daily-workflow",
    "cmd /c pnpm run verify:phase237a-personal-operator-console",
    "cmd /c pnpm run verify:phase199a-real-ui-trial-runtime-sync",
    "cmd /c pnpm run verify:phase107a-secret-safety",
    "cmd /c pnpm run verify:phase105a-user-journey",
    "cmd /c pnpm run health:phase12a",
    "cmd /c pnpm run doctor:phase13a",
    "cmd /c pnpm -r --if-present check",
  ],
  requiredEvidenceStatusPaths: [
    "apps/ai-gateway-service/evidence/phase-237a-personal-operator-console.json",
    "apps/ai-gateway-service/evidence/phase-238a-personal-daily-workflow.json",
    "apps/ai-gateway-service/evidence/phase-239a-personal-project-knowledge-pack.json",
    "apps/ai-gateway-service/evidence/phase-240a-personal-decision-dashboard.json",
    "apps/ai-gateway-service/evidence/phase-241a-personal-live-trial.json",
    "apps/ai-gateway-service/evidence/phase-242a-personal-action-queue.json",
    "apps/ai-gateway-service/evidence/phase-243a-personal-review-evidence-loop.json",
    "apps/ai-gateway-service/evidence/phase-244a-personal-operator-manual-final.json",
  ],
  conclusionPassed: "personal-value-line-preview-closure-ready",
  conclusionFailed: "personal-value-line-preview-closure-incomplete",
  capabilityList: [
    "personal-operator-console",
    "daily-workflow",
    "project-knowledge-pack",
    "decision-dashboard",
    "live-trial",
    "action-queue",
    "review-evidence-loop",
    "final-operator-manual",
    "closure-snapshot",
  ],
  notes: [
    "Phase 245A seals the preview-only personal value line.",
    "The closure snapshot records completed self-use capabilities, daily value, cannot-do boundaries, evidence index, and next decision gate.",
    "Recommended next route is Option B, but the system does not automatically enter it.",
  ],
});
