import { verifyPersonalValuePhase } from "./verifyPersonalValueClosureSupport.js";

await verifyPersonalValuePhase({
  phase: "phase-243a-personal-review-evidence-loop",
  docPath: "docs/PERSONAL_REVIEW_EVIDENCE_LOOP.md",
  verifierPath: "apps/ai-gateway-service/src/entrypoints/verifyPersonalReviewEvidenceLoop.js",
  rootScriptName: "verify:phase243a-personal-review-evidence-loop",
  serviceScriptValue: "node ./src/entrypoints/verifyPersonalReviewEvidenceLoop.js",
  requiredDocSections: [
    "# Personal Review And Evidence Loop",
    "## 2. First Read After Codex Result Returns",
    "## 3. Boundary Review",
    "## 4. Legacy Check",
    "## 5. PROJECT_CONTEXT.md Check",
    "## 6. Commit / Push Check",
    "## 7. Real Execution / Worktree / Workflow Runner Check",
    "## 8. Evidence Review",
    "## 9. Verification Review",
    "## 10. Pass / Blocked / Redo Decision",
    "## 11. Final A-M Summary Format",
    "## 12. Updating The Next Task Queue",
    "## 13. Avoiding Preview-only Overclaim",
  ],
  requiredDocMarkers: [
    "Codex result returns",
    "Check whether `legacy/` changed",
    "Check whether `PROJECT_CONTEXT.md` was created",
    "No automatic commit was made",
    "Real `codex exec` was not connected",
    "Evidence `.json` exists",
    "Phase verifier for the current phase",
    "passed",
    "blocked",
    "redo",
    "A. Prerequisite check conclusion",
    "M. Whether commit/push happened",
    "Do not write",
  ],
  requiredUiMarkers: [
    "phase243a-personal-review-evidence-loop",
    "Boundary review",
    "Verification review",
    "Evidence review",
    "Conclusion review",
    "Next task update",
  ],
  requiredVerificationCommands: [
    "cmd /c pnpm run verify:phase243a-personal-review-evidence-loop",
    "cmd /c pnpm run verify:phase242a-personal-action-queue",
    "cmd /c pnpm run verify:phase241a-personal-live-trial",
    "cmd /c pnpm run verify:phase240a-personal-decision-dashboard",
    "cmd /c pnpm run verify:phase239a-personal-project-knowledge-pack",
    "cmd /c pnpm run verify:phase238a-personal-daily-workflow",
    "cmd /c pnpm run verify:phase237a-personal-operator-console",
    "cmd /c pnpm run verify:phase199a-real-ui-trial-runtime-sync",
    "cmd /c pnpm run verify:phase107a-secret-safety",
    "cmd /c pnpm run verify:phase105a-user-journey",
    "cmd /c pnpm run health:phase12a",
    "cmd /c pnpm run doctor:phase13a",
    "cmd /c pnpm -r --if-present check",
  ],
  requiredEvidenceStatusPaths: [
    "apps/ai-gateway-service/evidence/phase-242a-personal-action-queue.json",
  ],
  conclusionPassed: "personal-review-evidence-loop-preview-ready",
  conclusionFailed: "personal-review-evidence-loop-incomplete",
  capabilityList: [
    "codex-result-first-read",
    "boundary-review",
    "verification-review",
    "evidence-review",
    "pass-blocked-redo-decision",
    "final-a-m-summary-format",
    "next-task-update",
  ],
  notes: [
    "Phase 243A defines the review, verification, evidence, and conclusion loop.",
    "Codex results remain claims until checked locally and supported by passing evidence.",
    "No real Codex exec, worktree, workflow runner, automatic commit/push, or production-ready claim is added.",
  ],
});
