import { verifyPersonalValuePhase } from "./verifyPersonalValueClosureSupport.js";

await verifyPersonalValuePhase({
  phase: "phase-241a-personal-live-trial",
  docPath: "docs/PERSONAL_LIVE_TRIAL.md",
  verifierPath: "apps/ai-gateway-service/src/entrypoints/verifyPersonalLiveTrial.js",
  rootScriptName: "verify:phase241a-personal-live-trial",
  serviceScriptValue: "node ./src/entrypoints/verifyPersonalLiveTrial.js",
  requiredDocSections: [
    "# Personal Live Trial",
    "## 2. Real Use Order After Opening The System",
    "## 3. Reading Personal Operator Console",
    "## 4. Using Daily Workflow",
    "## 5. Querying Project Knowledge Pack",
    "## 6. Using Decision Dashboard",
    "## 7. Generating Next Codex Task",
    "## 8. Reviewing Codex Result",
    "## 9. Confirming Evidence And Verification",
    "## 10. Stop Or Continue",
    "## 11. Dirty Workspace Handling",
  ],
  requiredDocMarkers: [
    "Start live trial",
    "Read current state",
    "Decide next action",
    "Generate handoff",
    "Review result",
    "Verify evidence",
    "Stop or continue",
    "Do not treat the console as an execution panel",
    "The live trial must not describe a dirty workspace as clean",
  ],
  requiredUiMarkers: [
    "phase241a-personal-live-trial",
    "Start live trial",
    "Read current state",
    "Decide next action",
    "Generate handoff",
    "Review result",
    "Verify evidence",
    "Stop or continue",
  ],
  requiredVerificationCommands: [
    "cmd /c pnpm run verify:phase241a-personal-live-trial",
    "cmd /c pnpm run verify:phase240a-personal-decision-dashboard",
    "cmd /c pnpm run verify:phase239a-personal-project-knowledge-pack",
    "cmd /c pnpm run verify:phase238a-personal-daily-workflow",
    "cmd /c pnpm run verify:phase237a-personal-operator-console",
    "cmd /c pnpm run verify:phase199a-real-ui-trial-runtime-sync",
    "cmd /c pnpm run verify:phase107a-secret-safety",
    "cmd /c pnpm run verify:phase105a-user-journey",
    "cmd /c pnpm run health:phase12a",
    "cmd /c pnpm run doctor:phase13a",
    "cmd /c pnpm -r --if-present check",
  ],
  requiredEvidenceStatusPaths: [
    "apps/ai-gateway-service/evidence/phase-240a-personal-decision-dashboard.json",
  ],
  conclusionPassed: "personal-live-trial-preview-ready",
  conclusionFailed: "personal-live-trial-incomplete",
  capabilityList: [
    "live-trial-use-order",
    "operator-console-reading",
    "daily-workflow-use",
    "knowledge-pack-query",
    "decision-dashboard-next-step",
    "manual-handoff-review-verify-stop",
  ],
  notes: [
    "Phase 241A records a preview-only live self-use trial flow.",
    "The live trial proves the manual route from current-state review to handoff, review, evidence, and stop/continue decision.",
    "No real Codex exec, worktree, workflow runner, automatic commit/push, or production RAG capability is added.",
  ],
});
