import { verifyPersonalKnowledgePhase } from "./verifyPersonalKnowledgeClosureSupport.js";

await verifyPersonalKnowledgePhase({
  phase: "phase-248a-personal-knowledge-query-templates",
  docPath: "docs/PERSONAL_KNOWLEDGE_QUERY_TEMPLATES.md",
  verifierPath: "apps/ai-gateway-service/src/entrypoints/verifyPersonalKnowledgeQueryTemplates.js",
  rootScriptName: "verify:phase248a-personal-knowledge-query-templates",
  serviceScriptValue: "node ./src/entrypoints/verifyPersonalKnowledgeQueryTemplates.js",
  requiredDocSections: [
    "# Personal Knowledge Query Templates",
    "## 1. Current Project Status",
    "## 2. Current Blocker",
    "## 3. Latest Completed Phase",
    "## 4. Sealed Capabilities",
    "## 5. Preview-only Capabilities",
    "## 6. Cannot-promised Capabilities",
    "## 7. Recommended Next Step",
    "## 8. Next Codex Task",
    "## 9. Required Verification Commands",
    "## 10. Latest Evidence",
    "## 11. Knowledge/RAG Boundary",
    "## 12. Commercialization Fit",
    "## 13. Real Codex Exec Fit",
    "## 14. Stop Expansion",
  ],
  requiredDocMarkers: [
    "question",
    "expected sources",
    "expected answer format",
    "stale evidence caution",
    "what not to conclude",
    "do not claim production vector RAG or GraphRAG",
    "do not claim real Codex exec is enabled",
    "do not continue when boundaries are unclear",
  ],
  requiredUiMarkers: [
    "phase248a-personal-knowledge-query-templates",
    "Status question",
    "Blocker question",
    "Phase question",
    "Verification question",
    "Boundary question",
    "Stop question",
  ],
  requiredVerificationCommands: [
    "cmd /c pnpm run verify:phase248a-personal-knowledge-query-templates",
  ],
  requiredEvidenceStatusPaths: [
    "apps/ai-gateway-service/evidence/phase-247a-personal-knowledge-starter-pack.json",
  ],
  conclusionPassed: "personal-knowledge-query-templates-preview-ready",
  conclusionFailed: "personal-knowledge-query-templates-preview-incomplete",
  capabilityList: [
    "knowledge-query-templates",
    "status-template",
    "blocker-template",
    "phase-template",
    "boundary-template",
    "stop-template",
  ],
  notes: [
    "Phase 248A defines daily self-use Knowledge/RAG query templates.",
    "Each template requires expected sources, answer format, stale evidence caution, and what not to conclude.",
  ],
});
