import { verifyPersonalKnowledgePhase } from "./verifyPersonalKnowledgeClosureSupport.js";

await verifyPersonalKnowledgePhase({
  phase: "phase-255a-personal-knowledge-value-closure",
  docPath: "docs/PERSONAL_KNOWLEDGE_VALUE_CLOSURE.md",
  verifierPath: "apps/ai-gateway-service/src/entrypoints/verifyPersonalKnowledgeValueClosure.js",
  rootScriptName: "verify:phase255a-personal-knowledge-value-closure",
  serviceScriptValue: "node ./src/entrypoints/verifyPersonalKnowledgeValueClosure.js",
  requiredDocSections: [
    "# Personal Knowledge Value Closure",
    "## 1. Final Self-use Knowledge Conclusion",
    "## 2. Completed Capability List",
    "## 3. Actual Value",
    "## 4. Current Cannot-do List",
    "## 5. Daily Entry",
    "## 6. Knowledge Query Checklist",
    "## 7. Evidence Index",
    "## 8. Next Optional Routes",
    "## 9. Recommended Next Route",
    "## 10. Final Boundary Statement",
  ],
  requiredDocMarkers: [
    "Source Inventory",
    "Starter Pack",
    "Query Templates",
    "Citation Report",
    "Freshness Guard",
    "UI Guide",
    "Live Trial",
    "Maintenance Loop",
    "Operator Manual",
    "Option A: Continue self-use UI polish.",
    "Option B: Enter Controlled Codex One-shot Readiness.",
    "Option C: Start real knowledge material import enhancement.",
    "Option D: Return to commercial Demo Pack.",
    "Recommended next route: Option B",
    "Do not automatically enter Option B.",
  ],
  requiredUiMarkers: [
    "phase255a-personal-knowledge-value-closure",
    "Knowledge baseline sealed",
    "What it helps me query",
    "What it will not do",
    "Next knowledge decision gate",
  ],
  requiredVerificationCommands: [
    "cmd /c pnpm run verify:phase255a-personal-knowledge-value-closure",
  ],
  requiredEvidenceStatusPaths: [
    "apps/ai-gateway-service/evidence/phase-246a-personal-knowledge-source-inventory.json",
    "apps/ai-gateway-service/evidence/phase-247a-personal-knowledge-starter-pack.json",
    "apps/ai-gateway-service/evidence/phase-248a-personal-knowledge-query-templates.json",
    "apps/ai-gateway-service/evidence/phase-249a-personal-knowledge-citation-report.json",
    "apps/ai-gateway-service/evidence/phase-250a-personal-knowledge-freshness-guard.json",
    "apps/ai-gateway-service/evidence/phase-251a-personal-knowledge-ui-guide.json",
    "apps/ai-gateway-service/evidence/phase-252a-personal-knowledge-live-trial.json",
    "apps/ai-gateway-service/evidence/phase-253a-personal-knowledge-maintenance-loop.json",
    "apps/ai-gateway-service/evidence/phase-254a-personal-knowledge-operator-manual.json",
  ],
  conclusionPassed: "personal-knowledge-value-line-preview-closure-ready",
  conclusionFailed: "personal-knowledge-value-line-preview-closure-incomplete",
  capabilityList: [
    "source-inventory",
    "starter-pack",
    "query-templates",
    "citation-report",
    "freshness-guard",
    "ui-guide",
    "live-trial",
    "maintenance-loop",
    "operator-manual",
    "knowledge-value-closure",
  ],
  notes: [
    "Phase 255A seals the self-use Knowledge/RAG value line.",
    "The closure records daily value, evidence index, cannot-do boundaries, and the next decision gate.",
    "Recommended next route is Option B, but the system does not automatically enter it.",
  ],
});
