import { verifyCodexOneShotReadinessPhase } from "./verifyCodexOneShotReadinessSupport.js";

await verifyCodexOneShotReadinessPhase({
  phase: "phase-261a-codex-result-intake-contract",
  docPath: "docs/CODEX_RESULT_INTAKE_CONTRACT.md",
  verifierPath: "apps/ai-gateway-service/src/entrypoints/verifyCodexResultIntakeContract.js",
  rootScriptName: "verify:phase261a-codex-result-intake-contract",
  serviceScriptValue: "node ./src/entrypoints/verifyCodexResultIntakeContract.js",
  requiredDocSections: [
    "# Codex Result Intake Contract",
    "## 1. Required Codex Result Contents",
    "## 2. Modified Files Format",
    "## 3. Executed Commands Format",
    "## 4. Verification Result Format",
    "## 5. Evidence Path Format",
    "## 6. Boundary Review Format",
    "## 7. Failure / Blocked Format",
    "## 8. A-M Summary Format",
    "## 9. Rejecting Incomplete Results",
    "## 10. Entering Review & Evidence Loop",
  ],
  requiredDocMarkers: [
    "modified files",
    "executed commands",
    "verification results",
    "evidence paths",
    "boundary review",
    "A-M summary",
    "codexExecInvoked=false",
    "workflowRunEnabled=false",
    "worktreeCreated=false",
    "autoCommit=false",
    "autoPush=false",
    "Reject incomplete results",
    "Review & Evidence Loop",
  ],
  requiredUiMarkers: [
    "phase261a-codex-result-intake-contract",
    "required result fields",
    "modified files",
    "executed commands",
    "verification results",
    "evidence paths",
    "boundary review",
    "reject incomplete result",
  ],
  requiredVerificationCommands: [
    "cmd /c pnpm run verify:phase261a-codex-result-intake-contract",
  ],
  requiredEvidenceStatusPaths: [
    "apps/ai-gateway-service/evidence/phase-260a-codex-dry-run-execution-plan.json",
  ],
  conclusionPassed: "codex-result-intake-contract-preview-ready",
  conclusionFailed: "codex-result-intake-contract-preview-incomplete",
  capabilityList: [
    "result-intake-contract",
    "modified-files-format",
    "executed-commands-format",
    "verification-format",
    "evidence-path-format",
    "boundary-review-format",
  ],
  notes: [
    "Phase 261A defines result intake requirements.",
    "Incomplete results are rejected before Review & Evidence Loop.",
  ],
});
