import { verifyPersonalKnowledgePhase } from "./verifyPersonalKnowledgeClosureSupport.js";

await verifyPersonalKnowledgePhase({
  phase: "phase-252a-personal-knowledge-live-trial",
  docPath: "docs/PERSONAL_KNOWLEDGE_LIVE_TRIAL.md",
  verifierPath: "apps/ai-gateway-service/src/entrypoints/verifyPersonalKnowledgeLiveTrial.js",
  rootScriptName: "verify:phase252a-personal-knowledge-live-trial",
  serviceScriptValue: "node ./src/entrypoints/verifyPersonalKnowledgeLiveTrial.js",
  requiredDocSections: [
    "# Personal Knowledge Live Trial",
    "## 1. Trial Goal",
    "## 2. Pre-trial Checks",
    "## 3. Recommended Sources",
    "## 4. Recommended Questions",
    "## 5. Expected Answer Format",
    "## 6. Citation Check",
    "## 7. Freshness Check",
    "## 8. Blocker Judgment",
    "## 9. Next Task Generation",
    "## 10. Stop Conditions",
    "## 11. Pass / Fail Decision",
  ],
  requiredDocMarkers: [
    "answers cite sources",
    "freshness is checked",
    "blocker is identified",
    "README",
    "AGENTS",
    "latest evidence",
    "Citation Check",
    "Freshness Check",
    "Do not continue when an answer claims production RAG or GraphRAG.",
  ],
  requiredUiMarkers: [
    "phase252a-personal-knowledge-live-trial",
    "Trial goal",
    "Pre-trial checks",
    "Recommended sources",
    "Recommended questions",
    "Citation and freshness checks",
    "Stop condition",
  ],
  requiredVerificationCommands: [
    "cmd /c pnpm run verify:phase252a-personal-knowledge-live-trial",
  ],
  requiredEvidenceStatusPaths: [
    "apps/ai-gateway-service/evidence/phase-251a-personal-knowledge-ui-guide.json",
  ],
  conclusionPassed: "personal-knowledge-live-trial-preview-ready",
  conclusionFailed: "personal-knowledge-live-trial-preview-incomplete",
  capabilityList: [
    "knowledge-live-trial",
    "pre-trial-checks",
    "recommended-sources",
    "recommended-questions",
    "citation-check",
    "freshness-check",
    "stop-condition",
  ],
  notes: [
    "Phase 252A defines a preview-only self-use knowledge query trial.",
    "The trial passes only when citation, freshness, blocker, next-task, and boundary checks hold.",
  ],
});
