import { verifyCodexOneShotReadinessPhase } from "./verifyCodexOneShotReadinessSupport.js";

await verifyCodexOneShotReadinessPhase({
  phase: "phase-262a-codex-rollback-stop-rules",
  docPath: "docs/CODEX_ROLLBACK_STOP_RULES.md",
  verifierPath: "apps/ai-gateway-service/src/entrypoints/verifyCodexRollbackStopRules.js",
  rootScriptName: "verify:phase262a-codex-rollback-stop-rules",
  serviceScriptValue: "node ./src/entrypoints/verifyCodexRollbackStopRules.js",
  requiredDocSections: [
    "# Codex Rollback And Stop Rules",
    "## 1. Immediate Stop Conditions",
    "## 2. Result Rejection Conditions",
    "## 3. Rollback Conditions",
    "## 4. Dirty Workspace No-auto-rollback Rule",
    "## 5. legacy/ Changed Rule",
    "## 6. PROJECT_CONTEXT.md Created Rule",
    "## 7. Secret Exposure Rule",
    "## 8. Verification Failure Rule",
    "## 9. Missing Evidence Rule",
    "## 10. Human Recovery Flow",
  ],
  requiredDocMarkers: [
    "Stop immediately when",
    "Reject a result",
    "Rollback may be considered only after human review",
    "Dirty workspace must not be auto-rolled back.",
    "If `legacy/` is changed",
    "If `PROJECT_CONTEXT.md` is created",
    "If a secret is exposed",
    "If verification fails",
    "If evidence is missing",
    "Human recovery flow",
  ],
  requiredUiMarkers: [
    "phase262a-codex-rollback-stop-rules",
    "immediate stop",
    "reject result",
    "rollback requires human",
    "dirty workspace no auto rollback",
    "legacy stop",
    "secret stop",
    "missing evidence stop",
  ],
  requiredVerificationCommands: [
    "cmd /c pnpm run verify:phase262a-codex-rollback-stop-rules",
  ],
  requiredEvidenceStatusPaths: [
    "apps/ai-gateway-service/evidence/phase-261a-codex-result-intake-contract.json",
  ],
  conclusionPassed: "codex-rollback-stop-rules-preview-ready",
  conclusionFailed: "codex-rollback-stop-rules-preview-incomplete",
  capabilityList: [
    "rollback-stop-rules",
    "immediate-stop",
    "reject-result",
    "dirty-workspace-no-auto-rollback",
    "legacy-stop",
    "secret-stop",
  ],
  notes: [
    "Phase 262A defines stop and rollback rules.",
    "It does not perform automatic rollback or execution.",
  ],
});
