import { verifyPersonalKnowledgePhase } from "./verifyPersonalKnowledgeClosureSupport.js";

await verifyPersonalKnowledgePhase({
  phase: "phase-254a-personal-knowledge-operator-manual",
  docPath: "docs/PERSONAL_KNOWLEDGE_OPERATOR_MANUAL.md",
  verifierPath: "apps/ai-gateway-service/src/entrypoints/verifyPersonalKnowledgeOperatorManual.js",
  rootScriptName: "verify:phase254a-personal-knowledge-operator-manual",
  serviceScriptValue: "node ./src/entrypoints/verifyPersonalKnowledgeOperatorManual.js",
  requiredDocSections: [
    "# Personal Knowledge Operator Manual",
    "## 1. Daily Knowledge Use",
    "## 2. First Source Selection",
    "## 3. Asking Project Status",
    "## 4. Asking Blocker",
    "## 5. Asking Next Step",
    "## 6. Reading Citations",
    "## 7. Reading Freshness",
    "## 8. Conflict Handling",
    "## 9. Generating Next Codex Task",
    "## 10. Maintaining Knowledge",
    "## 11. Current Cannot-promised List",
    "## 12. Common Query List",
    "## 13. Common Verification Commands",
    "## 14. Stop Rules",
  ],
  requiredDocMarkers: [
    "Every day:",
    "Start with README, AGENTS, closure docs, latest evidence, and package scripts.",
    "Trust answers only when citations point to current docs or passed evidence.",
    "Turn an answer into manual handoff text only.",
    "Do not promise production vector RAG.",
    "Do not promise GraphRAG.",
    "Do not promise enterprise ACL sync.",
    "Do not promise multi-tenant knowledge base.",
    "Do not promise unattended automatic development.",
  ],
  requiredUiMarkers: [
    "phase254a-personal-knowledge-operator-manual",
    "Daily knowledge use",
    "First source selection",
    "Citation and freshness",
    "Conflict handling",
    "Next Codex task",
    "Stop rules",
  ],
  requiredVerificationCommands: [
    "cmd /c pnpm run verify:phase254a-personal-knowledge-operator-manual",
  ],
  requiredEvidenceStatusPaths: [
    "apps/ai-gateway-service/evidence/phase-253a-personal-knowledge-maintenance-loop.json",
  ],
  conclusionPassed: "personal-knowledge-operator-manual-preview-ready",
  conclusionFailed: "personal-knowledge-operator-manual-preview-incomplete",
  capabilityList: [
    "knowledge-operator-manual",
    "daily-knowledge-use",
    "first-source-selection",
    "citation-freshness-reading",
    "conflict-handling",
    "stop-rules",
  ],
  notes: [
    "Phase 254A consolidates Phases 246A-253A into a daily self-use knowledge manual.",
    "The manual keeps Knowledge/RAG preview-only and manual.",
  ],
});
