import { verifyCodexOneShotReadinessPhase } from "./verifyCodexOneShotReadinessSupport.js";

await verifyCodexOneShotReadinessPhase({
  phase: "phase-265a-codex-one-shot-readiness-closure",
  docPath: "docs/CODEX_ONE_SHOT_READINESS_CLOSURE.md",
  verifierPath: "apps/ai-gateway-service/src/entrypoints/verifyCodexOneShotReadinessClosure.js",
  rootScriptName: "verify:phase265a-codex-one-shot-readiness-closure",
  serviceScriptValue: "node ./src/entrypoints/verifyCodexOneShotReadinessClosure.js",
  requiredDocSections: [
    "# Codex One-shot Readiness Closure",
    "## 1. Final Conclusion",
    "## 2. Completed Capability List",
    "## 3. Actual Value",
    "## 4. Current Cannot-do List",
    "## 5. Why Real Execution Is Still Not Default",
    "## 6. Next Decision Gate Before Real Execution",
    "## 7. Evidence Index",
    "## 8. Next Optional Routes",
    "## 9. Recommended Next Route",
    "## 10. Final Boundary Statement",
  ],
  requiredDocMarkers: [
    "readiness policy",
    "task safety classifier",
    "preflight checklist",
    "approval record preview",
    "dry-run execution plan",
    "result intake contract",
    "rollback & stop rules",
    "UI readiness panel",
    "operator manual",
    "Do not claim real Codex exec.",
    "Do not claim execution completed.",
    "executionEnabled=false",
    "codexExecInvoked=false",
    "Option A: Stay at readiness and continue self-use.",
    "Option B: Do real knowledge source import enhancement.",
    "Option C: Do a human-approved real one-shot trial in a separate future phase.",
    "Option D: Return to commercial demo pack.",
    "Recommended next route: Option A",
    "Do not automatically enter Option A, B, C, or D.",
  ],
  requiredUiMarkers: [
    "phase265a-codex-one-shot-readiness-closure",
    "readiness sealed",
    "what it helps decide",
    "what it will not do",
    "why not real execution",
    "next decision gate",
  ],
  requiredVerificationCommands: [
    "cmd /c pnpm run verify:phase265a-codex-one-shot-readiness-closure",
  ],
  requiredEvidenceStatusPaths: [
    "apps/ai-gateway-service/evidence/phase-256a-codex-one-shot-readiness-policy.json",
    "apps/ai-gateway-service/evidence/phase-257a-codex-task-safety-classifier.json",
    "apps/ai-gateway-service/evidence/phase-258a-codex-preflight-checklist.json",
    "apps/ai-gateway-service/evidence/phase-259a-codex-approval-record-preview.json",
    "apps/ai-gateway-service/evidence/phase-260a-codex-dry-run-execution-plan.json",
    "apps/ai-gateway-service/evidence/phase-261a-codex-result-intake-contract.json",
    "apps/ai-gateway-service/evidence/phase-262a-codex-rollback-stop-rules.json",
    "apps/ai-gateway-service/evidence/phase-263a-codex-one-shot-ui-readiness-panel.json",
    "apps/ai-gateway-service/evidence/phase-264a-codex-one-shot-operator-manual.json",
  ],
  conclusionPassed: "codex-one-shot-readiness-closure-preview-ready",
  conclusionFailed: "codex-one-shot-readiness-closure-preview-incomplete",
  capabilityList: [
    "readiness-policy",
    "task-safety-classifier",
    "preflight-checklist",
    "approval-record-preview",
    "dry-run-execution-plan",
    "result-intake-contract",
    "rollback-stop-rules",
    "ui-readiness-panel",
    "operator-manual",
    "readiness-closure",
  ],
  notes: [
    "Phase 265A seals Controlled Codex One-shot Readiness as preview-only.",
    "The system can judge readiness but still does not execute Codex.",
    "Recommended next route is Option A, but the system does not automatically enter it.",
  ],
});
