import { verifyCodexOneShotReadinessPhase } from "./verifyCodexOneShotReadinessSupport.js";

await verifyCodexOneShotReadinessPhase({
  phase: "phase-256a-codex-one-shot-readiness-policy",
  docPath: "docs/CODEX_ONE_SHOT_READINESS_POLICY.md",
  verifierPath: "apps/ai-gateway-service/src/entrypoints/verifyCodexOneShotReadinessPolicy.js",
  rootScriptName: "verify:phase256a-codex-one-shot-readiness-policy",
  serviceScriptValue: "node ./src/entrypoints/verifyCodexOneShotReadinessPolicy.js",
  requiredDocSections: [
    "# Codex One-shot Readiness Policy",
    "## 1. What One-shot Readiness Is",
    "## 2. What One-shot Execution Is Not",
    "## 3. Tasks Allowed Into Readiness",
    "## 4. Tasks Not Allowed Into Readiness",
    "## 5. Required Preconditions",
    "## 6. Required Human Confirmations",
    "## 7. Dirty Workspace Rule",
    "## 8. Secret Safety Rule",
    "## 9. legacy/ Rule",
    "## 10. PROJECT_CONTEXT.md Rule",
    "## 11. Commit / Push Rule",
    "## 12. Evidence Rule",
    "## 13. Failure Stop Rule",
  ],
  requiredDocMarkers: [
    "One-shot readiness is a visible checklist",
    "Readiness is not one-shot execution.",
    "executionEnabled=false.",
    "approval-preview is not execution permission",
    "Dirty workspace must remain visible.",
    "Do not modify `legacy/`.",
    "Do not create `PROJECT_CONTEXT.md`.",
    "Do not automatically commit or push.",
  ],
  requiredUiMarkers: [
    "phase256a-codex-one-shot-readiness-policy",
    "Readiness policy",
    "Not execution",
    "Allowed tasks",
    "Blocked tasks",
    "Human confirmation",
    "Failure stop rule",
  ],
  requiredVerificationCommands: [
    "cmd /c pnpm run verify:phase256a-codex-one-shot-readiness-policy",
  ],
  requiredEvidenceStatusPaths: [
    "apps/ai-gateway-service/evidence/phase-255a-personal-knowledge-value-closure.json",
  ],
  conclusionPassed: "codex-one-shot-readiness-policy-preview-ready",
  conclusionFailed: "codex-one-shot-readiness-policy-preview-incomplete",
  capabilityList: [
    "readiness-policy",
    "not-execution-boundary",
    "allowed-task-policy",
    "blocked-task-policy",
    "human-confirmation-policy",
    "failure-stop-rule",
  ],
  notes: [
    "Phase 256A defines preview-only one-shot readiness policy.",
    "It does not enable real Codex execution.",
  ],
});
