import { verifyPersonalValuePhase } from "./verifyPersonalValueClosureSupport.js";

await verifyPersonalValuePhase({
  phase: "phase-244a-personal-operator-manual-final",
  docPath: "docs/PERSONAL_OPERATOR_MANUAL_FINAL.md",
  verifierPath: "apps/ai-gateway-service/src/entrypoints/verifyPersonalOperatorManualFinal.js",
  rootScriptName: "verify:phase244a-personal-operator-manual-final",
  serviceScriptValue: "node ./src/entrypoints/verifyPersonalOperatorManualFinal.js",
  requiredDocSections: [
    "# Personal Operator Manual Final",
    "## 1. Daily Startup",
    "## 2. What To Read First",
    "## 3. Judging Current Status",
    "## 4. Generating The Next Codex Task",
    "## 5. Handing Work To Codex",
    "## 6. Importing Or Reading Codex Result",
    "## 7. Reviewing Result",
    "## 8. Running Verification",
    "## 9. Reading Evidence",
    "## 10. Updating The Next Step",
    "## 11. When To Stop",
    "## 12. Things That Must Never Be Default",
    "## 13. Common Commands",
    "## 14. Common Exception Handling",
    "## 15. Self-use Value Boundary",
  ],
  requiredDocMarkers: [
    "Every day",
    "Read in this order",
    "Do not call a dirty workspace clean",
    "Generate a task only when",
    "Use manual handoff only",
    "Read it manually first",
    "Stop if any required verification fails",
    "Evidence is sealed only when",
    "Never default to",
    "Dirty workspace",
    "Verification failure",
    "Evidence missing",
    "Boundary violation",
    "Commercial drift",
  ],
  requiredUiMarkers: [
    "phase244a-personal-operator-manual-final",
    "Daily use manual",
    "Commands",
    "Review checklist",
    "Stop rules",
    "Boundaries",
  ],
  requiredVerificationCommands: [
    "cmd /c pnpm run verify:phase244a-personal-operator-manual-final",
    "cmd /c pnpm run verify:phase243a-personal-review-evidence-loop",
    "cmd /c pnpm run verify:phase242a-personal-action-queue",
    "cmd /c pnpm run verify:phase241a-personal-live-trial",
    "cmd /c pnpm run verify:phase240a-personal-decision-dashboard",
    "cmd /c pnpm run verify:phase239a-personal-project-knowledge-pack",
    "cmd /c pnpm run verify:phase238a-personal-daily-workflow",
    "cmd /c pnpm run verify:phase237a-personal-operator-console",
    "cmd /c pnpm run verify:phase199a-real-ui-trial-runtime-sync",
    "cmd /c pnpm run verify:phase107a-secret-safety",
    "cmd /c pnpm run verify:phase105a-user-journey",
    "cmd /c pnpm run health:phase12a",
    "cmd /c pnpm run doctor:phase13a",
    "cmd /c pnpm -r --if-present check",
  ],
  requiredEvidenceStatusPaths: [
    "apps/ai-gateway-service/evidence/phase-243a-personal-review-evidence-loop.json",
  ],
  conclusionPassed: "personal-operator-manual-final-preview-ready",
  conclusionFailed: "personal-operator-manual-final-incomplete",
  capabilityList: [
    "daily-startup",
    "current-status-judgment",
    "manual-codex-task-generation",
    "codex-result-review",
    "verification-and-evidence",
    "stop-rules",
    "common-exception-handling",
  ],
  notes: [
    "Phase 244A consolidates the personal operator manual.",
    "The manual covers startup, status, task generation, handoff, review, verification, evidence, next step, stop rules, commands, and exceptions.",
    "No real execution, worktree, workflow runner, automatic commit/push, or production RAG claim is added.",
  ],
});
