import { verifyCodexOneShotReadinessPhase } from "./verifyCodexOneShotReadinessSupport.js";

await verifyCodexOneShotReadinessPhase({
  phase: "phase-258a-codex-preflight-checklist",
  docPath: "docs/CODEX_PREFLIGHT_CHECKLIST.md",
  verifierPath: "apps/ai-gateway-service/src/entrypoints/verifyCodexPreflightChecklist.js",
  rootScriptName: "verify:phase258a-codex-preflight-checklist",
  serviceScriptValue: "node ./src/entrypoints/verifyCodexPreflightChecklist.js",
  requiredDocSections: [
    "# Codex Preflight Checklist",
    "## 1. Workspace State Check",
    "## 2. Git Dirty State Check",
    "## 3. legacy/ Change Check",
    "## 4. PROJECT_CONTEXT.md Check",
    "## 5. Secret Scan Check",
    "## 6. Allowed Files Check",
    "## 7. Blocked Files Check",
    "## 8. Required Verification Check",
    "## 9. Expected Evidence Check",
    "## 10. Rollback / Stop Plan Check",
    "## 11. Human Approval Check",
    "## 12. Final Go / No-go Output Format",
  ],
  requiredDocMarkers: [
    "Do not describe dirty workspace as clean.",
    "Confirm `legacy/` is not in allowed files",
    "Confirm `PROJECT_CONTEXT.md` is not created",
    "Do not write real API keys.",
    "List exact files",
    "required verification",
    "expected evidence",
    "approval-preview must be present only as review metadata",
    "executionEnabled=false",
    "codexExecInvoked=false",
  ],
  requiredUiMarkers: [
    "phase258a-codex-preflight-checklist",
    "workspace status",
    "git dirty status",
    "allowed files",
    "blocked files",
    "required verification",
    "expected evidence",
    "rollback/stop plan",
    "go/no-go",
  ],
  requiredVerificationCommands: [
    "cmd /c pnpm run verify:phase258a-codex-preflight-checklist",
  ],
  requiredEvidenceStatusPaths: [
    "apps/ai-gateway-service/evidence/phase-257a-codex-task-safety-classifier.json",
  ],
  conclusionPassed: "codex-preflight-checklist-preview-ready",
  conclusionFailed: "codex-preflight-checklist-preview-incomplete",
  capabilityList: [
    "preflight-checklist",
    "workspace-check",
    "dirty-state-check",
    "allowed-files-check",
    "blocked-files-check",
    "go-no-go-format",
  ],
  notes: [
    "Phase 258A defines preview-only preflight checks.",
    "Go/no-go is readiness only and not execution permission.",
  ],
});
