import { verifyCodexOneShotReadinessPhase } from "./verifyCodexOneShotReadinessSupport.js";

await verifyCodexOneShotReadinessPhase({
  phase: "phase-260a-codex-dry-run-execution-plan",
  docPath: "docs/CODEX_DRY_RUN_EXECUTION_PLAN.md",
  verifierPath: "apps/ai-gateway-service/src/entrypoints/verifyCodexDryRunExecutionPlan.js",
  rootScriptName: "verify:phase260a-codex-dry-run-execution-plan",
  serviceScriptValue: "node ./src/entrypoints/verifyCodexDryRunExecutionPlan.js",
  requiredDocSections: [
    "# Codex Dry-run Execution Plan",
    "## 1. Dry-run Execution Plan Definition",
    "## 2. Inputs",
    "## 3. Outputs",
    "## 4. What It Will Not Execute",
    "## 5. What Files It Will Not Modify",
    "## 6. Commit / Push",
    "## 7. Codex CLI",
    "## 8. Plan Step Format",
    "## 9. Verification Command Format",
    "## 10. Evidence Expected Format",
    "## 11. Stop Condition",
    "## 12. Dry-run Failure Handling",
  ],
  requiredDocMarkers: [
    "non-executing plan",
    "task classification",
    "preflight result",
    "approval-preview record",
    "executionEnabled=false",
    "The dry-run plan will not execute Codex",
    "Do not execute codex command.",
    "Do not call real `codex exec`.",
    "expectedEvidence",
    "stopCondition",
  ],
  requiredUiMarkers: [
    "phase260a-codex-dry-run-execution-plan",
    "dry-run only",
    "inputs",
    "outputs",
    "no Codex CLI",
    "verification format",
    "expected evidence",
    "stop condition",
  ],
  requiredVerificationCommands: [
    "cmd /c pnpm run verify:phase260a-codex-dry-run-execution-plan",
  ],
  requiredEvidenceStatusPaths: [
    "apps/ai-gateway-service/evidence/phase-259a-codex-approval-record-preview.json",
  ],
  conclusionPassed: "codex-dry-run-execution-plan-preview-ready",
  conclusionFailed: "codex-dry-run-execution-plan-preview-incomplete",
  capabilityList: [
    "dry-run-execution-plan",
    "input-contract",
    "output-contract",
    "plan-step-format",
    "verification-format",
    "stop-condition",
  ],
  notes: [
    "Phase 260A defines a non-executing dry-run plan.",
    "No Codex CLI command is called.",
  ],
});
