export function formatWorkforcePlanMarkdown(plan) {
  return [
    "# Agent Workforce Plan Preview",
    "",
    `- Workforce ID: ${plan.workforceId}`,
    `- Plan version: ${plan.planVersion}`,
    `- Created at: ${plan.createdAt}`,
    `- Goal: ${plan.goal}`,
    `- Selected template: ${plan.selectedTemplate?.name || "Feature Development"}`,
    `- Status: ${plan.userFriendlyStatus}`,
    "",
    "## Product Templates Preview",
    `- Phase: ${plan.productTemplatesPreview.phase}`,
    `- Mode: ${plan.productTemplatesPreview.mode}`,
    `- Template pack enabled: ${plan.productTemplatesPreview.templatePackEnabled}`,
    `- Execution enabled: ${plan.productTemplatesPreview.executionEnabled}`,
    `- Selected template: ${plan.selectedTemplate?.id || plan.productTemplatesPreview.selectedTemplateId}`,
    ...plan.productTemplatesPreview.templates.map((item) => `- Template: ${item.name} (${item.id}) - ${item.description}; execution=${item.execution}`),
    ...plan.productTemplatesPreview.templates.flatMap((item) => [
      `- Sample goal for ${item.id}: ${item.sampleGoal}`,
      ...item.expectedPlanSections.map((section) => `  - Expected section: ${section}`),
      ...item.sampleAcceptanceChecklist.map((check) => `  - Sample acceptance: ${check}`),
    ]),
    ...plan.productTemplatesPreview.demoGoals.map((item) => `- Demo goal: ${item.templateName} - ${item.sampleGoal}; execution=${item.execution}`),
    ...plan.productTemplatesPreview.blockedReasons.map((item) => `- Blocker: ${item}`),
    "",
    "## Template Context",
    `- Phase: ${plan.templateContext.phase}`,
    `- Selected template: ${plan.templateContext.selectedTemplateName}`,
    `- Default goal prompt: ${plan.templateContext.defaultGoalPrompt}`,
    `- Execution enabled: ${plan.templateContext.executionEnabled}`,
    `- External runner dispatch enabled: ${plan.templateContext.externalRunnerDispatchEnabled}`,
    `- Workflow run enabled: ${plan.templateContext.workflowRunEnabled}`,
    ...plan.templateContext.focusAreas.map((item) => `- Focus area: ${item}`),
    ...plan.templateContext.expectedOutputs.map((item) => `- Expected output: ${item}`),
    ...plan.templateContext.expectedPlanSections.map((item) => `- Expected plan section: ${item}`),
    ...plan.templateContext.sampleAcceptanceChecklist.map((item) => `- Sample acceptance: ${item}`),
    "",
    "## Summary",
    plan.summary,
    "",
    "## Roles",
    ...plan.roleAssignments.map((item) => `- ${item.role}: ${item.responsibility}`),
    "",
    "## Role Tiers",
    ...plan.roleTiers.flatMap((tier) => [
      `- ${tier.name}: ${tier.purpose}`,
      ...tier.roles.map((role) => `  - ${role.role}: ${role.responsibility}`),
    ]),
    "",
    "## Clarification Questions",
    ...plan.clarifyQuestions.map((item) => `- ${item.topic}: ${item.question} (${item.why})`),
    "",
    "## Clarification Answers",
    ...plan.clarificationAnswers.map((item) => `- ${item.questionId}: ${item.answer || "(unanswered)"}`),
    "",
    "## Answered Clarifications",
    ...plan.answeredClarifications.map((item) => `- ${item.topic}: ${item.answer}`),
    "",
    "## Unresolved Clarifications",
    ...plan.unresolvedClarifications.map((item) => `- ${item.topic}: ${item.question}`),
    "",
    "## Consensus Preview",
    ...plan.consensusPreview.map((item) => `- ${item.role}: ${item.viewpoint} Recommendation: ${item.recommendation}`),
    "",
    "## Hook Events Preview",
    ...plan.hookEventsPreview.map((item) => `- ${item.event}: enabled=${item.enabled}; ${item.purpose}`),
    "",
    "## Event Ledger Preview",
    ...plan.eventLedgerPreview.map((item) => `- ${item.eventName}: enabled=${item.enabled}; execution=${item.execution}; ${item.payloadSummary}`),
    "",
    "## Agent Workforce HUD Preview",
    `- Phase: ${plan.workforceHudPreview.phase}`,
    `- Plan State: ${plan.workforceHudPreview.planState}`,
    `- Clarification: ${plan.workforceHudPreview.clarification.answered}/${plan.workforceHudPreview.clarification.total}`,
    `- Consensus: ${plan.workforceHudPreview.consensus.ready ? "ready" : "needs review"} (${plan.workforceHudPreview.consensus.roles.join(", ")})`,
    `- Review Package: ${plan.workforceHudPreview.reviewPackage.status}`,
    `- Approval Gate: ${plan.workforceHudPreview.approvalGate.status}`,
    `- Workflow Handoff: ${plan.workforceHudPreview.workflowHandoff.status}`,
    `- OMX Handoff: ${plan.workforceHudPreview.omxHandoff.status}`,
    `- Execution: ${plan.workforceHudPreview.execution.status}`,
    `- Execution Readiness: ${plan.workforceHudPreview.execution.readiness}`,
    "",
    "## OMX Handoff Preview",
    `- Phase: ${plan.omxHandoffPreview.phase}`,
    `- Mode: ${plan.omxHandoffPreview.mode}`,
    `- Status: ${plan.omxHandoffPreview.status}`,
    `- Execution enabled: ${plan.omxHandoffPreview.executionEnabled}`,
    `- Installs OMX: ${plan.omxHandoffPreview.installsOhMyCodex}`,
    `- Runs OMX: ${plan.omxHandoffPreview.runsOhMyCodex}`,
    `- Workflow: ${plan.omxHandoffPreview.recommendedWorkflow}`,
    ...plan.omxHandoffPreview.suggestedOmxCommands.map((item) => `- Suggested command: ${item}`),
    ...plan.omxHandoffPreview.blockedReasons.map((item) => `- Blocker: ${item}`),
    "",
    "## Execution Readiness Preflight",
    `- Phase: ${plan.executionReadinessPreflight.phase}`,
    `- Mode: ${plan.executionReadinessPreflight.mode}`,
    `- Overall status: ${plan.executionReadinessPreflight.overallStatus}`,
    `- Execution enabled: ${plan.executionReadinessPreflight.executionEnabled}`,
    ...plan.executionReadinessPreflight.checks.map((item) => `- ${item.name}: ${item.status}; required=${item.required}; ${item.reason}`),
    ...plan.executionReadinessPreflight.blockedReasons.map((item) => `- Blocker: ${item}`),
    `- Recommended next step: ${plan.executionReadinessPreflight.recommendedNextStep}`,
    "",
    "## External OMX Runner Design",
    `- Phase: ${plan.externalOmxRunnerDesign.phase}`,
    `- Mode: ${plan.externalOmxRunnerDesign.mode}`,
    `- Runner enabled: ${plan.externalOmxRunnerDesign.runnerEnabled}`,
    `- Execution enabled: ${plan.externalOmxRunnerDesign.executionEnabled}`,
    `- Design only: ${plan.externalOmxRunnerDesign.designOnly}`,
    ...plan.externalOmxRunnerDesign.proposedEndpoints.map((item) => `- Proposed endpoint: ${item.method} ${item.path}; execution=${item.execution}; ${item.purpose}`),
    ...plan.externalOmxRunnerDesign.requiredPreflightChecks.map((item) => `- Required preflight check: ${item}`),
    ...plan.externalOmxRunnerDesign.blockedReasons.map((item) => `- Blocker: ${item}`),
    "",
    "## Runner Request Review Queue Preview",
    `- Phase: ${plan.runnerRequestQueuePreview.phase}`,
    `- Mode: ${plan.runnerRequestQueuePreview.mode}`,
    `- Queue enabled: ${plan.runnerRequestQueuePreview.queueEnabled}`,
    `- Execution enabled: ${plan.runnerRequestQueuePreview.executionEnabled}`,
    `- Request state: ${plan.runnerRequestQueuePreview.requestState}`,
    `- Auto dispatch enabled: ${plan.runnerRequestQueuePreview.queuePolicy.autoDispatchEnabled}`,
    `- External runner dispatch enabled: ${plan.runnerRequestQueuePreview.queuePolicy.externalRunnerDispatchEnabled}`,
    `- Approval preview is execution permission: ${plan.runnerRequestQueuePreview.queuePolicy.approvalPreviewIsExecutionPermission}`,
    ...plan.runnerRequestQueuePreview.blockedReasons.map((item) => `- Blocker: ${item}`),
    `- Recommended next step: ${plan.runnerRequestQueuePreview.recommendedNextStep}`,
    "",
    "## Execution Request Approval Record Preview",
    `- Phase: ${plan.executionApprovalRecordPreview.phase}`,
    `- Mode: ${plan.executionApprovalRecordPreview.mode}`,
    `- Approval record enabled: ${plan.executionApprovalRecordPreview.approvalRecordEnabled}`,
    `- Execution enabled: ${plan.executionApprovalRecordPreview.executionEnabled}`,
    `- Approval state: ${plan.executionApprovalRecordPreview.approvalState}`,
    `- Approval preview is execution permission: ${plan.executionApprovalRecordPreview.approvalPolicy.approvalPreviewIsExecutionPermission}`,
    ...plan.executionApprovalRecordPreview.recordFieldsPreview.map((item) => `- Record field preview: ${item}`),
    ...plan.executionApprovalRecordPreview.blockedReasons.map((item) => `- Blocker: ${item}`),
    `- Recommended next step: ${plan.executionApprovalRecordPreview.recommendedNextStep}`,
    "",
    "## External Runner Protocol Freeze",
    `- Phase: ${plan.externalRunnerProtocolFreeze.phase}`,
    `- Mode: ${plan.externalRunnerProtocolFreeze.mode}`,
    `- Protocol version: ${plan.externalRunnerProtocolFreeze.protocolVersion}`,
    `- Frozen: ${plan.externalRunnerProtocolFreeze.frozen}`,
    `- Runner enabled: ${plan.externalRunnerProtocolFreeze.runnerEnabled}`,
    `- Execution enabled: ${plan.externalRunnerProtocolFreeze.executionEnabled}`,
    `- Design only: ${plan.externalRunnerProtocolFreeze.designOnly}`,
    ...plan.externalRunnerProtocolFreeze.coveredCapabilities.map((item) => `- Covered capability: ${item}`),
    ...plan.externalRunnerProtocolFreeze.frozenInvariants.map((item) => `- Frozen invariant: ${item}`),
    ...plan.externalRunnerProtocolFreeze.requiredBeforeRealExecution.map((item) => `- Required before real execution: ${item}`),
    ...plan.externalRunnerProtocolFreeze.blockedReasons.map((item) => `- Blocker: ${item}`),
    "",
    "## Agent Workforce Preview Final UX Seal",
    `- Phase: ${plan.agentWorkforcePreviewFinalUxSeal.phase}`,
    `- Mode: ${plan.agentWorkforcePreviewFinalUxSeal.mode}`,
    `- Sealed: ${plan.agentWorkforcePreviewFinalUxSeal.sealed}`,
    `- Preview only: ${plan.agentWorkforcePreviewFinalUxSeal.previewOnly}`,
    `- Execution enabled: ${plan.agentWorkforcePreviewFinalUxSeal.executionEnabled}`,
    `- Runner enabled: ${plan.agentWorkforcePreviewFinalUxSeal.runnerEnabled}`,
    `- Workflow run enabled: ${plan.agentWorkforcePreviewFinalUxSeal.workflowRunEnabled}`,
    `- External runner dispatch enabled: ${plan.agentWorkforcePreviewFinalUxSeal.externalRunnerDispatchEnabled}`,
    `- OMX execution enabled: ${plan.agentWorkforcePreviewFinalUxSeal.omxExecutionEnabled}`,
    ...plan.agentWorkforcePreviewFinalUxSeal.userPath.map((item) => `- User path: ${item}`),
    ...plan.agentWorkforcePreviewFinalUxSeal.finalUiMessages.map((item) => `- Final UX message: ${item}`),
    ...plan.agentWorkforcePreviewFinalUxSeal.blockedReasons.map((item) => `- Blocker: ${item}`),
    `- Recommended next step: ${plan.agentWorkforcePreviewFinalUxSeal.recommendedNextStep}`,
    "",
    "## Export / Handoff Explanation",
    "- Export is a handoff package for human review, not an execution package.",
    "- Suggested OMX commands are text only and are not executed.",
    "- approval-preview is not execution approval.",
    "- executionEnabled=false is preserved in the export.",
    "",
    "## Handoff Package Manifest",
    `- Phase: ${plan.handoffPackageManifest.phase}`,
    `- Mode: ${plan.handoffPackageManifest.mode}`,
    `- Manifest enabled: ${plan.handoffPackageManifest.manifestEnabled}`,
    `- Execution enabled: ${plan.handoffPackageManifest.executionEnabled}`,
    `- Runner enabled: ${plan.handoffPackageManifest.runnerEnabled}`,
    `- Workflow run enabled: ${plan.handoffPackageManifest.workflowRunEnabled}`,
    `- Purpose: ${plan.handoffPackageManifest.packagePurpose}`,
    ...plan.handoffPackageManifest.includedSections.map((item) => `- Included section: ${item}`),
    ...plan.handoffPackageManifest.externalRunnerDisabledReasons.map((item) => `- External runner disabled reason: ${item}`),
    ...plan.handoffPackageManifest.blockedReasons.map((item) => `- Blocker: ${item}`),
    "",
    "## Codex Desktop Handoff Pack",
    `- Phase: ${plan.codexDesktopHandoffPack.phase}`,
    `- Mode: ${plan.codexDesktopHandoffPack.mode}`,
    `- Manual copy/paste only: ${plan.codexDesktopHandoffPack.manualOnly}`,
    `- Codex execution enabled in web system: ${plan.codexDesktopHandoffPack.codexExecutionEnabled}`,
    `- Auto dispatch enabled: ${plan.codexDesktopHandoffPack.autoDispatchEnabled}`,
    `- Target: ${plan.codexDesktopHandoffPack.target}`,
    `- Copy/paste required: ${plan.codexDesktopHandoffPack.copyPasteRequired}`,
    `- Task goal: ${plan.codexDesktopHandoffPack.taskGoal}`,
    ...plan.codexDesktopHandoffPack.contextSummary.map((item) => `- Context: ${item}`),
    ...plan.codexDesktopHandoffPack.allowedFiles.map((item) => `- Allowed file: ${item}`),
    ...plan.codexDesktopHandoffPack.forbiddenActions.map((item) => `- Forbidden action: ${item}`),
    ...plan.codexDesktopHandoffPack.implementationConstraints.map((item) => `- Implementation constraint: ${item}`),
    ...plan.codexDesktopHandoffPack.verificationCommands.map((item) => `- Verification command: ${item}`),
    ...plan.codexDesktopHandoffPack.evidenceExpectations.map((item) => `- Evidence expectation: ${item}`),
    ...plan.codexDesktopHandoffPack.responseFormat.map((item) => `- Response format: ${item}`),
    ...plan.codexDesktopHandoffPack.blockedReasons.map((item) => `- Blocker: ${item}`),
    "",
    "## Manual Codex Execution Loop",
    `- Phase: ${plan.manualCodexExecutionLoop.phase}`,
    `- Mode: ${plan.manualCodexExecutionLoop.mode}`,
    `- Loop enabled: ${plan.manualCodexExecutionLoop.loopEnabled}`,
    `- Manual only: ${plan.manualCodexExecutionLoop.manualOnly}`,
    `- Codex execution enabled: ${plan.manualCodexExecutionLoop.codexExecutionEnabled}`,
    `- Auto run enabled: ${plan.manualCodexExecutionLoop.autoRunEnabled}`,
    ...plan.manualCodexExecutionLoop.steps.map((item) => `- Step: ${item}`),
    ...plan.manualCodexExecutionLoop.requiredHumanActions.map((item) => `- Required human action: ${item}`),
    ...plan.manualCodexExecutionLoop.blockedReasons.map((item) => `- Blocker: ${item}`),
    "",
    "## Codex Result Review Preview",
    `- Phase: ${plan.codexResultReviewPreview.phase}`,
    `- Mode: ${plan.codexResultReviewPreview.mode}`,
    `- Review enabled: ${plan.codexResultReviewPreview.reviewEnabled}`,
    `- Manual paste only: ${plan.codexResultReviewPreview.manualPasteOnly}`,
    `- Auto apply enabled: ${plan.codexResultReviewPreview.autoApplyEnabled}`,
    `- Auto merge enabled: ${plan.codexResultReviewPreview.autoMergeEnabled}`,
    `- Auto commit enabled: ${plan.codexResultReviewPreview.autoCommitEnabled}`,
    ...plan.codexResultReviewPreview.expectedResultSections.map((item) => `- Expected result section: ${item}`),
    ...plan.codexResultReviewPreview.reviewChecklist.map((item) => `- Review checklist: ${item}`),
    ...plan.codexResultReviewPreview.blockedReasons.map((item) => `- Blocker: ${item}`),
    "",
    "## Safe Desktop Runner Design",
    `- Phase: ${plan.safeDesktopRunnerDesign.phase}`,
    `- Mode: ${plan.safeDesktopRunnerDesign.mode}`,
    `- Runner implemented: ${plan.safeDesktopRunnerDesign.runnerImplemented}`,
    `- Runner enabled: ${plan.safeDesktopRunnerDesign.runnerEnabled}`,
    `- Codex CLI invocation enabled: ${plan.safeDesktopRunnerDesign.codexCliInvocationEnabled}`,
    `- Execution enabled: ${plan.safeDesktopRunnerDesign.executionEnabled}`,
    `- Design only: ${plan.safeDesktopRunnerDesign.designOnly}`,
    ...plan.safeDesktopRunnerDesign.requiredBeforeImplementation.map((item) => `- Required before implementation: ${item}`),
    ...plan.safeDesktopRunnerDesign.forbiddenByDefault.map((item) => `- Forbidden by default: ${item}`),
    ...plan.safeDesktopRunnerDesign.blockedReasons.map((item) => `- Blocker: ${item}`),
    "",
    "## Plan State / HUD",
    `- Current state: ${plan.planState.current}`,
    `- States: ${plan.planState.states.join(" -> ")}`,
    `- HUD: ${plan.planState.hud.summary}`,
    `- Workflow run handoff: ${plan.planState.workflowRunHandoff.status}`,
    "",
    "## Review Package Preview",
    `- Phase: ${plan.reviewPackagePreview.phase}`,
    `- Status: ${plan.reviewPackagePreview.status}`,
    `- Clarification coverage: ${plan.reviewPackagePreview.summary.clarificationCoverage}`,
    `- Workflow run handoff: ${plan.reviewPackagePreview.disabledWorkflowRunHandoff.status}`,
    "",
    "## Human Approval Gate Preview",
    `- Status: ${plan.approvalGatePreview.status}`,
    `- Allowed decisions: ${plan.approvalGatePreview.allowedDecisions.join(", ")}`,
    `- Execution enabled: ${plan.approvalGatePreview.executionEnabled}`,
    `- Workflow run enabled: ${plan.approvalGatePreview.workflowRunEnabled}`,
    "",
    "## Tasks",
    ...plan.taskBreakdown.map((item) => `- ${item.taskId} / ${item.role}: ${item.description}`),
    "",
    "## Deliverables",
    ...plan.deliverables.map((item) => `- ${item.title}: ${item.description} (${item.ownerRole})`),
    "",
    "## Acceptance Criteria",
    ...plan.acceptanceCriteria.map((item) => `- ${item}`),
    "",
    "## Risks",
    ...plan.risks.map((item) => `- ${item}`),
    "",
    "## Limitations",
    ...plan.limitations.map((item) => `- ${item}`),
    "",
    "## Next Actions",
    ...plan.nextActions.map((item) => `- ${item}`),
    "",
    "## Recommended Next Step",
    plan.recommendedNextStep,
    "",
    "## Safety",
    "- Preview only: true",
    "- Real LLM calls: false",
    "- Code execution: false",
    "- Project file writes: false",
    "- Workflow run: false",
  ].join("\n");
}

export function createExportableWorkforcePlan(plan) {
  return {
    phase: plan.phase,
    planVersion: plan.planVersion,
    createdAt: plan.createdAt,
    mode: plan.mode,
    workforceId: plan.workforceId,
    goal: plan.goal,
    summary: plan.summary,
    userFriendlyStatus: plan.userFriendlyStatus,
    selectedRoles: plan.selectedRoles,
    selectedTemplate: plan.selectedTemplate,
    templateContext: plan.templateContext,
    productTemplatesPreview: plan.productTemplatesPreview,
    roleTiers: plan.roleTiers,
    clarifyQuestions: plan.clarifyQuestions,
    consensusPreview: plan.consensusPreview,
    hookEventsPreview: plan.hookEventsPreview,
    eventLedgerPreview: plan.eventLedgerPreview,
    planState: plan.planState,
    clarificationAnswers: plan.clarificationAnswers,
    answeredClarifications: plan.answeredClarifications,
    unresolvedClarifications: plan.unresolvedClarifications,
    lifecyclePreview: plan.lifecyclePreview,
    omxHandoffPreview: plan.omxHandoffPreview,
    executionReadinessPreflight: plan.executionReadinessPreflight,
    externalOmxRunnerDesign: plan.externalOmxRunnerDesign,
    runnerRequestQueuePreview: plan.runnerRequestQueuePreview,
    executionApprovalRecordPreview: plan.executionApprovalRecordPreview,
    externalRunnerProtocolFreeze: plan.externalRunnerProtocolFreeze,
    agentWorkforcePreviewFinalUxSeal: plan.agentWorkforcePreviewFinalUxSeal,
    handoffPackageManifest: plan.handoffPackageManifest,
    codexDesktopHandoffPack: plan.codexDesktopHandoffPack,
    manualCodexExecutionLoop: plan.manualCodexExecutionLoop,
    codexResultReviewPreview: plan.codexResultReviewPreview,
    safeDesktopRunnerDesign: plan.safeDesktopRunnerDesign,
    workforceHudPreview: plan.workforceHudPreview,
    reviewPackagePreview: plan.reviewPackagePreview,
    approvalGatePreview: plan.approvalGatePreview,
    taskBreakdown: plan.taskBreakdown,
    roleAssignments: plan.roleAssignments,
    deliverables: plan.deliverables,
    acceptanceCriteria: plan.acceptanceCriteria,
    risks: plan.risks,
    limitations: plan.limitations,
    nextActions: plan.nextActions,
    recommendedNextStep: plan.recommendedNextStep,
    safety: plan.safety,
    meta: plan.meta,
  };
}
