export function buildNetworkAttemptEvidenceSchema() {
  return {
    phase: "Phase903",
    networkAttemptEvidenceSchemaReady: true,
    requiredFields: [
      "requestId",
      "providerId",
      "modelId",
      "credentialRef",
      "credentialRefOnly",
      "rawSecretRead",
      "authJsonRead",
      "networkAttemptRecorded",
      "outboundAttemptAt",
      "adapterName",
      "adapterMode",
      "providerRequestId",
      "providerRequestIdUnavailableReason",
      "responseReceived",
      "responseSource",
      "httpStatusClass",
      "responseMarkerMatched",
      "mockResponseUsed",
      "simulatedResponseUsed",
      "dryRunOnly",
      "localExecutorOnly",
    ],
    example: {
      requestId: "internal route request id",
      providerId: "nvidia",
      modelId: "nvidia/model-id",
      credentialRef: "credentialRef:nvidia:default",
      credentialRefOnly: true,
      rawSecretRead: false,
      authJsonRead: false,
      networkAttemptRecorded: true,
      outboundAttemptAt: "ISO timestamp",
      adapterName: "provider adapter name",
      adapterMode: "external_provider",
      providerRequestId: null,
      providerRequestIdUnavailableReason: "provider did not return request id; adapter outbound trace is required",
      outboundTracePresent: true,
      responseReceived: true,
      responseSource: "external_provider",
      httpStatusClass: "2xx",
      responseMarkerMatched: true,
      mockResponseUsed: false,
      simulatedResponseUsed: false,
      dryRunOnly: false,
      localExecutorOnly: false,
    },
  };
}
