export function buildRealRouteQualityBlockedEvidence({ gate = {}, scenarioPack = {} } = {}) {
  return {
    phaseRange: "Phase916-930",
    completed: true,
    recommended_sealed: false,
    blocker: gate.blocker || "phase916_930_approval_missing",
    approvalPresent: gate.approvalPresent === true,
    authorizationComplete: gate.authorizationComplete === true,
    scenarioPackReady: scenarioPack.scenarioPackReady === true,
    providerCallsMade: false,
    totalProviderRequests: 0,
    maxTotalProviderRequests: gate.maxTotalProviderRequests || 20,
    maxTotalProviderRequestsRespected: true,
    maxRequestsPerMode: gate.maxRequestsPerMode || 6,
    maxRequestsPerModel: gate.maxRequestsPerModel || 3,
    maxEstimatedCostUsdTotal: gate.maxEstimatedCostUsdTotal || 1,
    maxRetries: 0,
    maxRetriesPerRequest: 0,
    maxRetriesRespected: true,
    estimatedCostUsdTotal: 0,
    budgetExceeded: false,
    providerId: "nvidia",
    providerAllowlist: gate.providerAllowlist || ["nvidia"],
    credentialRef: "credentialRef:nvidia:default",
    credentialRefOnly: true,
    externalProviderApiCallConfirmedFromPhase912915: true,
    externalProviderApiCallConfirmed: false,
    networkAttemptRecorded: false,
    providerResponseReceived: false,
    responseSource: "unknown",
    routeQualityTestExecuted: false,
    routeQualityEvidenceReady: false,
    realRouteQualityTestExecuted: false,
    normalModeRouteTestPassed: false,
    godModeRouteTestPassed: false,
    tianshuModeRouteTestPassed: false,
    fallbackRouteTestPassed: false,
    routeQualityScoringReady: false,
    selectableModelCountBefore: 0,
    selectableModelCountAfter: 0,
    unauthorizedSelectableChangeDetected: false,
    blockedHighRiskModelsExcluded: true,
    failedModelsExcluded: true,
    credentialMissingModelsExcludedFromRuntime: true,
    noBroaderExecutionWithoutNewApproval: true,
    mockResponseUsed: false,
    simulatedResponseUsed: false,
    dryRunOnly: false,
    localExecutorOnly: false,
    rawSecretRead: false,
    secretValueExposed: false,
    authJsonRead: false,
    chatBehaviorChangedByDefault: false,
    chatGatewayExecuteBehaviorChangedByDefault: false,
    deployExecuted: false,
    releaseExecuted: false,
    tagCreated: false,
    artifactUploaded: false,
    unsupportedClaimCount: 0,
    hallucinatedFactCount: 0,
  };
}

export function buildRealRouteQualityDecision({ finalEvidence = {} } = {}) {
  return {
    phase: "Phase930",
    recommended_sealed: finalEvidence.recommended_sealed === true,
    blocker: finalEvidence.blocker || null,
    nextAction: finalEvidence.recommended_sealed === true
      ? "review_quality_scores_before_any_default_route_change"
      : "collect_phase916_930_approval_before_broader_real_route_quality_test",
    requiresNewApproval: finalEvidence.recommended_sealed !== true,
    providerCallsMade: finalEvidence.providerCallsMade === true,
  };
}
