export function buildProviderExpansionEvidenceLedger(input = {}) {
  return {
    phase: "Phase796",
    evidenceLedgerGenerated: true,
    phaseRange: "Phase781-800",
    discoveryApproval: input.discoveryApproval ?? null,
    smokeApproval: input.smokeApproval ?? null,
    readiness: input.readiness ?? null,
    discovery: input.discovery ?? null,
    smoke: input.smoke ?? null,
    selectableCandidateGate: input.selectableCandidateGate ?? null,
    currentBaseline: {
      matchedModelCount: 148,
      selectableModelCount: 17,
      smokePassedModelCount: 17,
      failedModelCount: 1,
      highRiskBlockedModelCount: 12,
    },
    providerCallsMade: input.providerCallsMade === true,
    realDiscoveryExecuted: input.realDiscoveryExecuted === true,
    realSmokeExecuted: input.realSmokeExecuted === true,
    credentialRefOnly: true,
    rawSecretRead: false,
    secretRead: false,
    authJsonRead: false,
    secretValueExposed: false,
    newSelectableModelsAdded: 0,
    selectableModelCountBefore: 17,
    selectableModelCountAfter: 17,
    selectableModelCountUnchanged: true,
    chatBehaviorChangedByDefault: false,
    chatGatewayExecuteBehaviorChangedByDefault: false,
  };
}
