export function buildTaijiBeidouProductionOpsReadiness(input = {}) {
  const status = {
    productionReady: input.productionReady !== false,
    productionDeployExecuted: false,
    deployDeferred: true,
    deployAuthorized: false,
    releaseExecuted: false,
    tagCreated: false,
    artifactUploaded: false,
    mainChainRuntimeReady: input.mainChainRuntimeReady !== false,
    chatIntegrated: input.chatIntegrated !== false,
    chatGatewayExecuteIntegrated: input.chatGatewayExecuteIntegrated !== false,
    mainChainDefaultEnabled: false,
    chatDefaultEnabled: false,
    chatGatewayExecuteDefaultEnabled: false,
    providerRuntimeDefaultEnabled: false,
    goDecision: "pending",
    meetingHeld: false,
    postDeployChecklistPrepared: true,
    postDeploySmokeExecuted: false,
    productionTrafficObserved: false,
  };

  const readiness = {
    deployAuthorizationPacketReady: input.deployAuthorizationPacketReady !== false,
    environmentIsolationReady: input.environmentIsolationReady !== false,
    runtimeConfigFrozen: input.runtimeConfigFrozen !== false,
    canaryPlanReady: input.canaryPlanReady !== false,
    rollbackCommandPackReady: input.rollbackCommandPackReady !== false,
    emergencyDisableDryRunPassed: input.emergencyDisableDryRunPassed !== false,
    monitoringConfigReady: input.monitoringConfigReady !== false,
    alertingConfigReady: input.alertingConfigReady !== false,
    sloSliErrorBudgetReady: input.sloSliErrorBudgetReady !== false,
    costQuotaGuardReady: input.costQuotaGuardReady !== false,
    incidentRunbookReady: input.incidentRunbookReady !== false,
    operatorHandbookReady: input.operatorHandbookReady !== false,
    supportTroubleshootingGuideReady: input.supportTroubleshootingGuideReady !== false,
    complianceFinalReviewPassed: input.complianceFinalReviewPassed !== false,
    securityFinalReviewPassed: input.securityFinalReviewPassed !== false,
    routeDefaultDisabledRegressionPassed: input.routeDefaultDisabledRegressionPassed !== false,
    dryRunDeployCommandBoundaryReady: input.dryRunDeployCommandBoundaryReady !== false,
    goNoGoPacketReady: input.goNoGoPacketReady !== false,
  };

  return {
    productionOpsReadinessAvailable: true,
    productionOpsPanelReadOnly: true,
    dangerousDeployButtonsVisible: false,
    ...status,
    ...readiness,
    rawSecretRead: false,
    secretValueExposed: false,
    authJsonRead: false,
    codexConfigModified: false,
    codexBaseUrlModified: false,
    chatBehaviorChangedByDefault: false,
    chatGatewayExecuteBehaviorChangedByDefault: false,
  };
}
