export const MODE_POLICY_ERROR_CODES = Object.freeze({
  USER_MODE_NOT_ALLOWED: "USER_MODE_NOT_ALLOWED",
  USER_PROVIDER_NOT_ALLOWED: "USER_PROVIDER_NOT_ALLOWED",
  USER_MODEL_NOT_ALLOWED: "USER_MODEL_NOT_ALLOWED",
  USER_QUOTA_EXCEEDED: "USER_QUOTA_EXCEEDED",
  USER_BUDGET_EXCEEDED: "USER_BUDGET_EXCEEDED",
  REQUEST_COST_TOO_HIGH: "REQUEST_COST_TOO_HIGH",
  GOD_PARTICIPANT_LIMIT_EXCEEDED: "GOD_PARTICIPANT_LIMIT_EXCEEDED",
  TIANSHU_ESCALATION_NOT_ALLOWED: "TIANSHU_ESCALATION_NOT_ALLOWED",
  AUDIT_TRACE_REQUIRED: "AUDIT_TRACE_REQUIRED",
});

export class ModePolicyError extends Error {
  constructor(code, message, details = {}) {
    super(message);
    this.name = "ModePolicyError";
    this.code = code;
    this.details = details;
  }
}
