export const BILLING_ERROR_CODES = Object.freeze({
  DAILY_BUDGET_LIMIT_EXCEEDED: "DAILY_BUDGET_LIMIT_EXCEEDED",
  MONTHLY_BUDGET_LIMIT_EXCEEDED: "MONTHLY_BUDGET_LIMIT_EXCEEDED",
  REQUEST_COST_ABOVE_CONFIRMATION_THRESHOLD: "REQUEST_COST_ABOVE_CONFIRMATION_THRESHOLD",
});
