// The JSON-LD date injector must refuse pages it does not own, must refuse clones with no history, and
// must never move more than the two date lines. These arms run in both kinds of checkout: an earlier arm
// of mine passed locally and failed in CI because a local fixture and a runner's checkout disagreed, so
// the branch here is chosen by a measurement both environments can make the same way.
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { readFileSync, readdirSync } from "node:fs";
import { test } from "node:test";

const TOOL = "tools/inject-jsonld-dates.mjs";
const run = (args) => spawnSync(process.execPath, [TOOL, ...args], { encoding: "utf8" });
const depth = Number(spawnSync("git", ["rev-list", "--count", "HEAD"], { encoding: "utf8" }).stdout.trim());
const hasHistory = Number.isSafeInteger(depth) && depth > 1;

test("the decision follows the clone's history depth, in either direction", () => {
  const r = run(["docs/prompt-enhancement.html", "--dry"]);
  if (hasHistory) {
    assert.equal(r.status, 0, r.stdout + r.stderr);
    assert.match(r.stdout, /DRY RUN/, r.stdout);
    assert.match(r.stdout, /datePublished \S+ -> \d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z/, "the plan must print full UTC values: " + r.stdout);
    // Shape, not numbers: which lines move depends on where the page currently sits, and pinning them turns
    // a correct run red the first time anyone commits the page again.
    assert.match(r.stdout, /lines_changed (none|\d+(,\d+)*\b)/, "the plan must name the lines it will touch: " + r.stdout);
    assert.match(r.stdout, /modified_from=max\(/, "the plan must say where dateModified came from: " + r.stdout);
  } else {
    assert.equal(r.status, 2, "a one-commit clone must be refused rather than guessed: " + r.stdout);
    assert.match(r.stdout, /one-commit clone/, r.stdout);
  }
});

test("a generator-owned page is refused, not rewritten", () => {
  const r = run(["docs/multi-arch-node-modules.html", "--dry"]);
  assert.equal(r.status, 2, "expected a refusal, got: " + r.stdout + r.stderr);
  assert.match(r.stdout, /generator-owned/, r.stdout);
});

test("running it with no target fails loudly instead of doing nothing quietly", () => {
  const r = run([]);
  assert.equal(r.status, 2, r.stdout + r.stderr);
  assert.match(r.stdout + r.stderr, /usage/, r.stdout + r.stderr);
});

test("every hand-authored page with a JSON-LD block carries git-shaped UTC dates", () => {
  // One page was fixed by hand and eleven more were found carrying the same defect, so the arm covers the
  // class. The floor keeps a broken discovery (zero candidates) from passing vacuously.
  const UTC = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$/u;
  const checked = [];
  for (const name of readdirSync("docs").filter((f) => f.endsWith(".html"))) {
    const html = readFileSync("docs/" + name, "utf8");
    if (html.includes("generated by tools/render-evidence-page.mjs")) continue; // the generator owns those
    const block = /<script type="application\/ld\+json">([\s\S]*?)<\/script>/u.exec(html);
    if (!block) continue; // pages with no block at all are issue #191's part A, not this arm
    const object = JSON.parse(block[1]);
    if (!object.datePublished && !object.dateModified) continue; // landing pages describe a software object
    checked.push(name);
    assert.match(String(object.datePublished), UTC, name + " datePublished is not full UTC: " + object.datePublished);
    assert.match(String(object.dateModified), UTC, name + " dateModified is not full UTC: " + object.dateModified);
    assert.ok(object.datePublished <= object.dateModified, name + ": published after modified " + object.datePublished + " / " + object.dateModified);
  }
  assert.ok(checked.length >= 12, "expected at least 12 dated hand-authored pages, saw " + checked.length + ": " + checked.join(","));

  // The same instant is published four times on these pages - twice in JSON-LD and twice as Open Graph
  // article:*_time. A page whose structured date is right but whose meta still claims a midnight that never
  // happened is still publishing a wrong timestamp, so both are pinned to the same form.
  let metaValues = 0;
  for (const name of readdirSync("docs").filter((f) => f.endsWith(".html"))) {
    const html = readFileSync("docs/" + name, "utf8");
    for (const m of html.matchAll(/<meta property="article:(?:published|modified)_time" content="([^"]*)"/gu)) {
      metaValues += 1;
      assert.match(m[1], UTC, name + " article:*_time is not a full UTC instant: " + m[1]);
    }
  }
  assert.ok(metaValues >= 28, "expected at least 28 Open Graph timestamps across the site, saw " + metaValues);
});
